# Machine Learning in Computational Biology - Assignment #2 - Spring 2026

## Imports

In [16]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from pathlib import Path
import sys
import warnings

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

project_dir = Path.cwd().parent
utils_dir = project_dir / 'src'

if str(utils_dir) not in sys.path:
    sys.path.append(str(utils_dir))

import functions
import rnCV_class

warnings.filterwarnings("ignore", category=UserWarning)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
dataset_raw = functions.load_data('students_dataset.csv')

X = dataset_raw.drop('num', axis=1)
y = dataset_raw['num']

print(f"Dataset shape : {dataset_raw.shape}")
print(f"Class counts : {y.value_counts().to_dict()}")

Dataset shape : (242, 14)
Class counts : {0: 131, 1: 111}

## Task 3 - Nested Cross-Validation Implementation

### Task 3.2 - Assess Generalization Performance and Select the Winner Algorithm

In [3]:
ALGORITHMS = [
    ("LR_ElasticNet", LogisticRegression(), functions.lr_space),
    ("GNB", GaussianNB(), functions.gnb_space),
    ("LDA", LinearDiscriminantAnalysis(), functions.lda_space),
    ("RandomForest", RandomForestClassifier(random_state=42), functions.rf_space),
    ("LightGBM", LGBMClassifier(random_state=42), functions.lgbm_space),
    ("XGBoost", XGBClassifier(random_state=42), functions.xgb_space),
    ("CatBoost", CatBoostClassifier(random_seed=42, verbose=0), functions.catboost_space),
]

print(f"{len(ALGORITHMS)} classifiers registered:")
print([name for name, _, _ in ALGORITHMS])

7 classifiers registered:
['LR_ElasticNet', 'GNB', 'LDA', 'RandomForest', 'LightGBM', 'XGBoost', 'CatBoost']

In [4]:
# Initialize rnCV class with desired parameters
rncv = rnCV_class.HeartDiseasernCV(n_rounds=10, n_outer=5, n_inner=3)

print(f"n_rounds : {rncv.n_rounds}")
print(f"n_outer  : {rncv.n_outer}  (evaluation folds per round)")
print(f"n_inner  : {rncv.n_inner}  (hyperparameter-tuning folds)")
print(f"Total evaluation points per algorithm : {rncv.n_rounds * rncv.n_outer}")
print("  (= 10 rounds x 5 outer folds)")

n_rounds : 10
n_outer  : 5  (evaluation folds per round)
n_inner  : 3  (hyperparameter-tuning folds)
Total evaluation points per algorithm : 50
  (= 10 rounds x 5 outer folds)

In [8]:
baseline_results = {}

for name, clf, space_fn in ALGORITHMS:
    print(f"Baseline {name} ...", end=" ", flush=True)
    baseline_results[name] = rncv.run_assessment(
        X, y,
        estimator_name = name,
        estimator = clf,
        param_space_func = space_fn,
        perform_fs = False,
        tune = False, # inner loop disabled
    )
    med = baseline_results[name]["mcc"].median()
    print(f"done | Median MCC = {med:.3f}")

print("\nBaseline complete.")

Baseline LR_ElasticNet ... done | Median MCC = 0.631
Baseline GNB ... done | Median MCC = 0.477
Baseline LDA ... done | Median MCC = 0.631
Baseline RandomForest ... done | Median MCC = 0.583
Baseline LightGBM ... [LightGBM] [Info] Number of positive: 88, number of negative: 105
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000133 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 215
[LightGBM] [Info] Number of data points in the train set: 193, number of used features: 18
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.455959 -> initscore=-0.176624
[LightGBM] [Info] Start training from score -0.176624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 89, number of negative: 104
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 218
[LightGBM] [Info] Number of data points in the train set: 193, number of used features: 18
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.461140 -> initscore=-0.155755
[LightGBM] [Info] Start training from score -0.155755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 89, number of negative: 105
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000296 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 217
[LightGBM] [Info] Number of data points in the train set: 194, number of used features: 18
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.458763 -> initscore=-0.165324
[LightGBM] [Info] Start training from score -0.165324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [9]:
rncv_results = {}

for name, clf, space_fn in ALGORITHMS:
    print(f"rnCV {name} ...", end=" ", flush=True)
    rncv_results[name] = rncv.run_assessment(
        X, y,
        estimator_name = name,
        estimator = clf,
        param_space_func = space_fn,
        perform_fs = False,
        tune = True, # inner Optuna loop active
    )
    med = rncv_results[name]["mcc"].median()
    print(f"done | Median MCC = {med:.3f}")

print("\nrnCV complete.")

rnCV LR_ElasticNet ...

[I 2026-05-13 22:19:20,122] A new study created in memory with name: no-name-9941fafa-c837-40d7-9b33-388270fe5996

[I 2026-05-13 22:19:20,226] Trial 0 finished with value: 0.674264007597341 and parameters: {'C': 0.05547119471592124, 'l1_ratio': 0.7151893663724195}. Best is trial 0 with value: 0.674264007597341.
[I 2026-05-13 22:19:20,314] Trial 1 finished with value: 0.7915315846350329 and parameters: {'C': 0.10323260351976568, 'l1_ratio': 0.5448831829968969}. Best is trial 1 with value: 0.7915315846350329.
[I 2026-05-13 22:19:20,381] Trial 2 finished with value: 0.0 and parameters: {'C': 0.013130280280658591, 'l1_ratio': 0.6458941130666561}. Best is trial 1 with value: 0.7915315846350329.
[I 2026-05-13 22:19:20,447] Trial 3 finished with value: 0.0 and parameters: {'C': 0.015414734761917091, 'l1_ratio': 0.8917730007820798}. Best is trial 1 with value: 0.7915315846350329.
[I 2026-05-13 22:19:20,587] Trial 4 finished with value: 0.8115975422427035 and parameters: {'C': 6.581332043291798, 'l1_ratio': 0.3834415188257777}. Best is trial 4 with value: 0.8115975422427035.
[I 2026-05-13 22:19:20,681] Trial 5 finished with value: 0.8413978494623655 and parameters: {'C': 0.9091283280651462, 'l1_ratio': 0.5288949197529045}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:20,750] Trial 6 finished with value: 0.6724396171204683 and parameters: {'C': 0.0692185991020861, 'l1_ratio': 0.925596638292661}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:20,812] Trial 7 finished with value: 0.0 and parameters: {'C': 0.00022655846366566662, 'l1_ratio': 0.08712929970154071}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:20,874] Trial 8 finished with value: 0.0 and parameters: {'C': 0.00012620948285169316, 'l1_ratio': 0.832619845547938}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:20,981] Trial 9 finished with value: 0.8225666806311968 and parameters: {'C': 0.7776492451078378, 'l1_ratio': 0.8700121482468192}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:21,128] Trial 10 finished with value: 0.8115975422427035 and parameters: {'C': 6.309902667927621, 'l1_ratio': 0.32439267355527085}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:21,216] Trial 11 finished with value: 0.8305916305916305 and parameters: {'C': 0.704127082636723, 'l1_ratio': 0.17940541166241886}. Best is trial 5 with value: 0.8413978494623655.
[I 2026-05-13 22:19:21,304] Trial 12 finished with value: 0.8424963924963924 and parameters: {'C': 0.92211123246997, 'l1_ratio': 0.05798087152647741}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,395] Trial 13 finished with value: 0.8346878927524087 and parameters: {'C': 0.7143218707895722, 'l1_ratio': 0.3411336894097175}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,488] Trial 14 finished with value: 0.8424963924963924 and parameters: {'C': 0.983016435636575, 'l1_ratio': 0.0347885812671269}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,557] Trial 15 finished with value: 0.0 and parameters: {'C': 0.00133418229997721, 'l1_ratio': 0.031737359391673284}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,636] Trial 16 finished with value: 0.803478978210161 and parameters: {'C': 0.24881355651574522, 'l1_ratio': 0.17021560542820185}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,743] Trial 17 finished with value: 0.8182539682539683 and parameters: {'C': 2.322407377543771, 'l1_ratio': 0.000827983885760511}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,812] Trial 18 finished with value: 0.0 and parameters: {'C': 0.004807162353322879, 'l1_ratio': 0.22578222117927643}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:21,893] Trial 19 finished with value: 0.7922398589065255 and parameters: {'C': 0.22389918466373976, 'l1_ratio': 0.10936635858090585}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,014] Trial 20 finished with value: 0.8182539682539683 and parameters: {'C': 2.310412177423549, 'l1_ratio': 0.2513073060534657}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,115] Trial 21 finished with value: 0.8373015873015873 and parameters: {'C': 1.2242692226875667, 'l1_ratio': 0.4736441904568497}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,203] Trial 22 finished with value: 0.7773784566237397 and parameters: {'C': 0.19585050614529478, 'l1_ratio': 0.4784433560535162}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,346] Trial 23 finished with value: 0.8139367235292533 and parameters: {'C': 2.7980268494877305, 'l1_ratio': 0.6554419933187521}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,442] Trial 24 finished with value: 0.8106619187264349 and parameters: {'C': 0.4713340442486114, 'l1_ratio': 0.4123243221543611}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,608] Trial 25 finished with value: 0.8115975422427035 and parameters: {'C': 7.128814705857842, 'l1_ratio': 0.5553480134273255}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,713] Trial 26 finished with value: 0.8231922398589065 and parameters: {'C': 1.8599254974266894, 'l1_ratio': 0.10020140694150917}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,804] Trial 27 finished with value: 0.8106619187264349 and parameters: {'C': 0.3747422443560864, 'l1_ratio': 0.2746367718897486}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,877] Trial 28 finished with value: 0.0 and parameters: {'C': 0.02447116767678034, 'l1_ratio': 0.988166412193483}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:22,965] Trial 29 finished with value: 0.7836132220033148 and parameters: {'C': 0.11374268532424457, 'l1_ratio': 0.7110232003082515}. Best is trial 12 with value: 0.8424963924963924.
[I 2026-05-13 22:19:23,029] A new study created in memory with name: no-name-6b30057d-20ed-4ee5-a4cb-a2a4b6cce587
[I 2026-05-13 22:19:23,110] Trial 0 finished with value: 0.0 and parameters: {'C': 0.012164941464151846, 'l1_ratio': 0.7203244934421581}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,173] Trial 1 finished with value: 0.0 and parameters: {'C': 0.00010013176560941267, 'l1_ratio': 0.30233257263183977}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,246] Trial 2 finished with value: 0.0 and parameters: {'C': 0.0005417257182767973, 'l1_ratio': 0.0923385947687978}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,306] Trial 3 finished with value: 0.0 and parameters: {'C': 0.0008536916958038761, 'l1_ratio': 0.34556072704304774}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,374] Trial 4 finished with value: 0.0 and parameters: {'C': 0.009634681692624377, 'l1_ratio': 0.538816734003357}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,455] Trial 5 finished with value: 0.0 and parameters: {'C': 0.012473047378928964, 'l1_ratio': 0.6852195003967595}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,525] Trial 6 finished with value: 0.0 and parameters: {'C': 0.001052594868979971, 'l1_ratio': 0.8781174363909454}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,590] Trial 7 finished with value: 0.0 and parameters: {'C': 0.00013706859653339875, 'l1_ratio': 0.6704675101784022}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,648] Trial 8 finished with value: 0.0 and parameters: {'C': 0.012204612973233806, 'l1_ratio': 0.5586898284457517}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,764] Trial 9 finished with value: 0.0 and parameters: {'C': 0.0005034249005866116, 'l1_ratio': 0.1981014890848788}. Best is trial 0 with value: 0.0.
[I 2026-05-13 22:19:23,907] Trial 10 finished with value: 0.7954344018033485 and parameters: {'C': 2.763907972870685, 'l1_ratio': 0.9684879328973564}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,067] Trial 11 finished with value: 0.7940400111141984 and parameters: {'C': 6.854509927653264, 'l1_ratio': 0.9876561817847485}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,236] Trial 12 finished with value: 0.7940400111141984 and parameters: {'C': 7.869332934202664, 'l1_ratio': 0.9843673710401255}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,363] Trial 13 finished with value: 0.7909450639806773 and parameters: {'C': 3.612585250855118, 'l1_ratio': 0.9933903683238319}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,470] Trial 14 finished with value: 0.7601835047388587 and parameters: {'C': 0.7287233626010106, 'l1_ratio': 0.7846191963614245}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,561] Trial 15 finished with value: 0.7572025675473951 and parameters: {'C': 0.2781062966824872, 'l1_ratio': 0.8570280810365645}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,667] Trial 16 finished with value: 0.7647783251231527 and parameters: {'C': 0.8780024020340315, 'l1_ratio': 0.9084593639351312}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,739] Trial 17 finished with value: 0.7822646280273399 and parameters: {'C': 0.11158061548390924, 'l1_ratio': 0.4217673537594471}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:24,878] Trial 18 finished with value: 0.7824678370168338 and parameters: {'C': 2.7786173953271387, 'l1_ratio': 0.7966858928208991}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,085] Trial 19 finished with value: 0.7876647834274954 and parameters: {'C': 9.400029606698721, 'l1_ratio': 0.6125301208952185}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,155] Trial 20 finished with value: 0.650146750524109 and parameters: {'C': 0.0720951405171715, 'l1_ratio': 0.9913614807124984}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,332] Trial 21 finished with value: 0.7940400111141984 and parameters: {'C': 8.869306496704743, 'l1_ratio': 0.9922862508044595}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,486] Trial 22 finished with value: 0.7824678370168338 and parameters: {'C': 3.1218287931948496, 'l1_ratio': 0.8862457120192744}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,596] Trial 23 finished with value: 0.7526077471631011 and parameters: {'C': 1.1036306372909963, 'l1_ratio': 0.7680938698502141}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,723] Trial 24 finished with value: 0.7779784991941625 and parameters: {'C': 1.8400282840280962, 'l1_ratio': 0.9357870850331554}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,809] Trial 25 finished with value: 0.7499430394167236 and parameters: {'C': 0.30041884086543863, 'l1_ratio': 0.7958241625837086}. Best is trial 10 with value: 0.7954344018033485.
[I 2026-05-13 22:19:25,983] Trial 26 finished with value: 0.7985208215564349 and parameters: {'C': 5.748104347389457, 'l1_ratio': 0.8385163092692209}. Best is trial 26 with value: 0.7985208215564349.
[I 2026-05-13 22:19:26,072] Trial 27 finished with value: 0.7425837320574162 and parameters: {'C': 0.45630551784270945, 'l1_ratio': 0.8501548269742627}. Best is trial 26 with value: 0.7985208215564349.
[I 2026-05-13 22:19:26,221] Trial 28 finished with value: 0.7779784991941625 and parameters: {'C': 3.7801006340987007, 'l1_ratio': 0.624490869008532}. Best is trial 26 with value: 0.7985208215564349.
[I 2026-05-13 22:19:26,298] Trial 29 finished with value: 0.7534029877403142 and parameters: {'C': 0.1400367291343302, 'l1_ratio': 0.705745130346066}. Best is trial 26 with value: 0.7985208215564349.
[I 2026-05-13 22:19:26,398] A new study created in memory with name: no-name-96ee8919-81d9-4157-9719-e309f1988d75
[I 2026-05-13 22:19:26,466] Trial 0 finished with value: 0.7566666666666667 and parameters: {'C': 0.015134724182275542, 'l1_ratio': 0.025926231827891333}. Best is trial 0 with value: 0.7566666666666667.
[I 2026-05-13 22:19:26,534] Trial 1 finished with value: 0.723366705172635 and parameters: {'C': 0.056016038175032964, 'l1_ratio': 0.4353223926182769}. Best is trial 0 with value: 0.7566666666666667.
[I 2026-05-13 22:19:26,597] Trial 2 finished with value: 0.14634146341463414 and parameters: {'C': 0.012642676064986638, 'l1_ratio': 0.3303348210038741}. Best is trial 0 with value: 0.7566666666666667.
[I 2026-05-13 22:19:26,659] Trial 3 finished with value: 0.2078853046594982 and parameters: {'C': 0.0010549774340694123, 'l1_ratio': 0.6192709663506637}. Best is trial 0 with value: 0.7566666666666667.
[I 2026-05-13 22:19:26,722] Trial 4 finished with value: 0.0 and parameters: {'C': 0.003149730300397854, 'l1_ratio': 0.26682727510286663}. Best is trial 0 with value: 0.7566666666666667.
[I 2026-05-13 22:19:26,798] Trial 5 finished with value: 0.7661240596867677 and parameters: {'C': 0.1275466815572558, 'l1_ratio': 0.5291420942770391}. Best is trial 5 with value: 0.7661240596867677.
[I 2026-05-13 22:19:26,869] Trial 6 finished with value: 0.4184116204489719 and parameters: {'C': 0.0004708685960549637, 'l1_ratio': 0.5135781212657464}. Best is trial 5 with value: 0.7661240596867677.
[I 2026-05-13 22:19:26,941] Trial 7 finished with value: 0.2078853046594982 and parameters: {'C': 0.0008359866231585379, 'l1_ratio': 0.7853351478166735}. Best is trial 5 with value: 0.7661240596867677.
[I 2026-05-13 22:19:27,049] Trial 8 finished with value: 0.778582182785021 and parameters: {'C': 1.8615575338558814, 'l1_ratio': 0.4942368373819278}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,157] Trial 9 finished with value: 0.7743474580421292 and parameters: {'C': 1.7092572346673058, 'l1_ratio': 0.079645477009061}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,316] Trial 10 finished with value: 0.7579009433962264 and parameters: {'C': 6.441808847399973, 'l1_ratio': 0.945159209595704}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,460] Trial 11 finished with value: 0.7659469204077206 and parameters: {'C': 3.393003617218319, 'l1_ratio': 0.0050289462424731035}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,569] Trial 12 finished with value: 0.7708414957990509 and parameters: {'C': 0.64559077756148, 'l1_ratio': 0.18901095863739453}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,695] Trial 13 finished with value: 0.7708414957990509 and parameters: {'C': 0.8019920282049252, 'l1_ratio': 0.7060818577828105}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,805] Trial 14 finished with value: 0.7781010239297225 and parameters: {'C': 0.46308717905625396, 'l1_ratio': 0.16248992554072827}. Best is trial 8 with value: 0.778582182785021.
[I 2026-05-13 22:19:27,907] Trial 15 finished with value: 0.7858290857326539 and parameters: {'C': 0.17092463833420043, 'l1_ratio': 0.37425491836579483}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:27,992] Trial 16 finished with value: 0.7780368779404458 and parameters: {'C': 0.17937171671193664, 'l1_ratio': 0.3763737139455026}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,071] Trial 17 finished with value: 0.4184116204489719 and parameters: {'C': 0.00011623198123514668, 'l1_ratio': 0.5937262337516113}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,159] Trial 18 finished with value: 0.7555727878094114 and parameters: {'C': 0.167024042188128, 'l1_ratio': 0.8469651252668152}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,321] Trial 19 finished with value: 0.7579009433962264 and parameters: {'C': 9.263015299724083, 'l1_ratio': 0.4325033763262549}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,434] Trial 20 finished with value: 0.7743474580421292 and parameters: {'C': 1.6941054341010062, 'l1_ratio': 0.2714057156923817}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,522] Trial 21 finished with value: 0.7781010239297225 and parameters: {'C': 0.44899827564823863, 'l1_ratio': 0.15643737676927408}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,597] Trial 22 finished with value: 0.7529687666560069 and parameters: {'C': 0.04809823761530183, 'l1_ratio': 0.18143329910073047}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,674] Trial 23 finished with value: 0.7770227141811841 and parameters: {'C': 0.25218861668060116, 'l1_ratio': 0.3002553969058894}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,770] Trial 24 finished with value: 0.778582182785021 and parameters: {'C': 1.5085900049702734, 'l1_ratio': 0.41990999308353383}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:28,898] Trial 25 finished with value: 0.7743474580421292 and parameters: {'C': 2.0430638371759815, 'l1_ratio': 0.41260173021741847}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:29,051] Trial 26 finished with value: 0.7659469204077206 and parameters: {'C': 3.462495173163211, 'l1_ratio': 0.6234308097396356}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:29,156] Trial 27 finished with value: 0.7708414957990509 and parameters: {'C': 1.0484636844734279, 'l1_ratio': 0.48586101953144945}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:29,236] Trial 28 finished with value: 0.7083098052196714 and parameters: {'C': 0.09592578343711335, 'l1_ratio': 0.6915891950491816}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:29,308] Trial 29 finished with value: 0.05882352941176471 and parameters: {'C': 0.017090846973211064, 'l1_ratio': 0.5637993096267739}. Best is trial 15 with value: 0.7858290857326539.
[I 2026-05-13 22:19:29,354] A new study created in memory with name: no-name-06001e8a-149d-4b8d-969b-bd64cc2355cb
[I 2026-05-13 22:19:29,431] Trial 0 finished with value: 0.7055505279034691 and parameters: {'C': 0.05675309007891905, 'l1_ratio': 0.7081478226181048}. Best is trial 0 with value: 0.7055505279034691.
[I 2026-05-13 22:19:29,502] Trial 1 finished with value: 0.0 and parameters: {'C': 0.0028478931734312097, 'l1_ratio': 0.510827605197663}. Best is trial 0 with value: 0.7055505279034691.
[I 2026-05-13 22:19:29,659] Trial 2 finished with value: 0.76739965130015 and parameters: {'C': 2.915645854219332, 'l1_ratio': 0.8962930889334381}. Best is trial 2 with value: 0.76739965130015.
[I 2026-05-13 22:19:29,732] Trial 3 finished with value: 0.0 and parameters: {'C': 0.00042454775855513846, 'l1_ratio': 0.20724287813818676}. Best is trial 2 with value: 0.76739965130015.
[I 2026-05-13 22:19:29,803] Trial 4 finished with value: 0.0 and parameters: {'C': 0.0001808572889594268, 'l1_ratio': 0.44080984365063647}. Best is trial 2 with value: 0.76739965130015.
[I 2026-05-13 22:19:29,876] Trial 5 finished with value: 0.0 and parameters: {'C': 0.00014105258653666057, 'l1_ratio': 0.4568332243947111}. Best is trial 2 with value: 0.76739965130015.
[I 2026-05-13 22:19:29,959] Trial 6 finished with value: 0.7994891443167305 and parameters: {'C': 0.17608413898610667, 'l1_ratio': 0.2784872826479753}. Best is trial 6 with value: 0.7994891443167305.
[I 2026-05-13 22:19:30,068] Trial 7 finished with value: 0.7873214016592599 and parameters: {'C': 0.2405883035834913, 'l1_ratio': 0.5908628174163508}. Best is trial 6 with value: 0.7994891443167305.
[I 2026-05-13 22:19:30,145] Trial 8 finished with value: 0.0 and parameters: {'C': 0.00013179817962229672, 'l1_ratio': 0.558854087990882}. Best is trial 6 with value: 0.7994891443167305.
[I 2026-05-13 22:19:30,222] Trial 9 finished with value: 0.0 and parameters: {'C': 0.001978163729123874, 'l1_ratio': 0.41510119701006964}. Best is trial 6 with value: 0.7994891443167305.

done | Median MCC = 0.627
rnCV GNB ...

[I 2026-05-13 22:22:30,488] A new study created in memory with name: no-name-f5e65163-a8b0-40e6-9bd3-b9fcbb089002
[I 2026-05-13 22:22:30,595] Trial 0 finished with value: 0.7645536206255846 and parameters: {'var_smoothing': 5.5471194715921156e-09}. Best is trial 0 with value: 0.7645536206255846.
[I 2026-05-13 22:22:30,687] Trial 1 finished with value: 0.7723169416881385 and parameters: {'var_smoothing': 3.766576841599302e-08}. Best is trial 1 with value: 0.7723169416881385.
[I 2026-05-13 22:22:30,774] Trial 2 finished with value: 0.7683899377611345 and parameters: {'var_smoothing': 1.032326035197657e-08}. Best is trial 1 with value: 0.7723169416881385.
[I 2026-05-13 22:22:30,860] Trial 3 finished with value: 0.7645536206255846 and parameters: {'var_smoothing': 5.30170934757682e-09}. Best is trial 1 with value: 0.7723169416881385.
[I 2026-05-13 22:22:30,952] Trial 4 finished with value: 0.7699631197059698 and parameters: {'var_smoothing': 1.3130280280658582e-09}. Best is trial 1 with value: 0.7723169416881385.
[I 2026-05-13 22:22:31,040] Trial 5 finished with value: 0.7659158037080531 and parameters: {'var_smoothing': 1.6961746387290984e-08}. Best is trial 1 with value: 0.7723169416881385.
[I 2026-05-13 22:22:31,130] Trial 6 finished with value: 0.7699631197059698 and parameters: {'var_smoothing': 1.541473476191711e-09}. Best is trial 1 with value: 0.7723169416881385.
[I 2026-05-13 22:22:31,216] Trial 7 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 2.8765041432546974e-07}. Best is trial 7 with value: 0.7889099406340786.
[I 2026-05-13 22:22:31,301] Trial 8 finished with value: 0.7932368637110017 and parameters: {'var_smoothing': 6.581332043291806e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,390] Trial 9 finished with value: 0.7662364116314356 and parameters: {'var_smoothing': 8.26432892700772e-10}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,480] Trial 10 finished with value: 0.7461884318884735 and parameters: {'var_smoothing': 2.101331318459538e-11}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,568] Trial 11 finished with value: 0.7932368637110017 and parameters: {'var_smoothing': 8.501917955916244e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,656] Trial 12 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 5.806190813539093e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,741] Trial 13 finished with value: 0.791290893015031 and parameters: {'var_smoothing': 1.2845526573509037e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,833] Trial 14 finished with value: 0.7932368637110017 and parameters: {'var_smoothing': 6.967948641461061e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:31,927] Trial 15 finished with value: 0.7830245325098645 and parameters: {'var_smoothing': 9.042294263425609e-08}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:32,021] Trial 16 finished with value: 0.743874885465338 and parameters: {'var_smoothing': 2.2296658046127727e-10}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:32,122] Trial 17 finished with value: 0.7932368637110017 and parameters: {'var_smoothing': 8.572745405580054e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:32,224] Trial 18 finished with value: 0.7870950888192269 and parameters: {'var_smoothing': 9.479012554617069e-08}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:32,354] Trial 19 finished with value: 0.7690736984448953 and parameters: {'var_smoothing': 3.0704669047156475e-08}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:32,568] Trial 20 finished with value: 0.7461884318884735 and parameters: {'var_smoothing': 1.5386479499673624e-11}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:32,780] Trial 21 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 2.8336645406180855e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,078] Trial 22 finished with value: 0.7932368637110017 and parameters: {'var_smoothing': 9.91001495170641e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,263] Trial 23 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 2.478777921461682e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,435] Trial 24 finished with value: 0.7756490409106486 and parameters: {'var_smoothing': 5.482584935738611e-08}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,567] Trial 25 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 4.269186338438708e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,672] Trial 26 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 1.8687237587316242e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,773] Trial 27 finished with value: 0.7405427862428278 and parameters: {'var_smoothing': 5.469972849811182e-11}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,881] Trial 28 finished with value: 0.7889099406340786 and parameters: {'var_smoothing': 5.604783260715666e-07}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:33,989] Trial 29 finished with value: 0.7790736984448952 and parameters: {'var_smoothing': 8.085891819642874e-08}. Best is trial 8 with value: 0.7932368637110017.
[I 2026-05-13 22:22:34,052] A new study created in memory with name: no-name-6e36380b-b849-4e98-a0f1-ffb420476545
[I 2026-05-13 22:22:34,155] Trial 0 finished with value: 0.6413611693803483 and parameters: {'var_smoothing': 1.2164941464151838e-09}. Best is trial 0 with value: 0.6413611693803483.
[I 2026-05-13 22:22:34,266] Trial 1 finished with value: 0.6452413024544094 and parameters: {'var_smoothing': 3.995972283135055e-08}. Best is trial 1 with value: 0.6452413024544094.
[I 2026-05-13 22:22:34,374] Trial 2 finished with value: 0.6022609819121447 and parameters: {'var_smoothing': 1.0013176560941244e-11}. Best is trial 1 with value: 0.6452413024544094.
[I 2026-05-13 22:22:34,488] Trial 3 finished with value: 0.648555820542612 and parameters: {'var_smoothing': 3.248350345086677e-10}. Best is trial 3 with value: 0.648555820542612.
[I 2026-05-13 22:22:34,664] Trial 4 finished with value: 0.6114035087719298 and parameters: {'var_smoothing': 5.4172571827679696e-11}. Best is trial 3 with value: 0.648555820542612.
[I 2026-05-13 22:22:34,861] Trial 5 finished with value: 0.613997113997114 and parameters: {'var_smoothing': 2.8952960233492744e-11}. Best is trial 3 with value: 0.648555820542612.
[I 2026-05-13 22:22:35,006] Trial 6 finished with value: 0.6114035087719298 and parameters: {'var_smoothing': 8.536916958038762e-11}. Best is trial 3 with value: 0.648555820542612.
[I 2026-05-13 22:22:35,112] Trial 7 finished with value: 0.6513687600644121 and parameters: {'var_smoothing': 5.34322712559411e-10}. Best is trial 7 with value: 0.6513687600644121.
[I 2026-05-13 22:22:35,225] Trial 8 finished with value: 0.6473601260835303 and parameters: {'var_smoothing': 9.634681692624362e-10}. Best is trial 7 with value: 0.6513687600644121.
[I 2026-05-13 22:22:35,366] Trial 9 finished with value: 0.6447146234380278 and parameters: {'var_smoothing': 4.944059287398678e-09}. Best is trial 7 with value: 0.6513687600644121.
[I 2026-05-13 22:22:35,522] Trial 10 finished with value: 0.6708817908817909 and parameters: {'var_smoothing': 5.882294859245768e-07}. Best is trial 10 with value: 0.6708817908817909.
[I 2026-05-13 22:22:35,651] Trial 11 finished with value: 0.6733582649779265 and parameters: {'var_smoothing': 7.854682797729162e-07}. Best is trial 11 with value: 0.6733582649779265.
[I 2026-05-13 22:22:35,746] Trial 12 finished with value: 0.6697840614037229 and parameters: {'var_smoothing': 6.854509927653269e-07}. Best is trial 11 with value: 0.6733582649779265.
[I 2026-05-13 22:22:35,840] Trial 13 finished with value: 0.6733582649779265 and parameters: {'var_smoothing': 8.675228225733071e-07}. Best is trial 11 with value: 0.6733582649779265.
[I 2026-05-13 22:22:35,952] Trial 14 finished with value: 0.6708496732026145 and parameters: {'var_smoothing': 8.980067676243825e-08}. Best is trial 11 with value: 0.6733582649779265.
[I 2026-05-13 22:22:36,061] Trial 15 finished with value: 0.6708496732026145 and parameters: {'var_smoothing': 9.358746983829253e-08}. Best is trial 11 with value: 0.6733582649779265.
[I 2026-05-13 22:22:36,169] Trial 16 finished with value: 0.6510512819485993 and parameters: {'var_smoothing': 1.3810502633729835e-08}. Best is trial 11 with value: 0.6733582649779265.
[I 2026-05-13 22:22:36,274] Trial 17 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 2.9940062793347445e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,367] Trial 18 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 1.2630178794522245e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,458] Trial 19 finished with value: 0.6708496732026145 and parameters: {'var_smoothing': 9.092849023454931e-08}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,561] Trial 20 finished with value: 0.6510512819485993 and parameters: {'var_smoothing': 1.5479971277996327e-08}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,659] Trial 21 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 2.526004638648932e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,758] Trial 22 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 2.2493743587414183e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,854] Trial 23 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 1.5842318298164066e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:36,934] Trial 24 finished with value: 0.6510512819485993 and parameters: {'var_smoothing': 2.20658113653863e-08}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:37,009] Trial 25 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 2.809187246598733e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:37,085] Trial 26 finished with value: 0.6447146234380278 and parameters: {'var_smoothing': 5.8660261930753645e-09}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:37,167] Trial 27 finished with value: 0.6452413024544094 and parameters: {'var_smoothing': 3.5631593188602107e-08}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:37,258] Trial 28 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 2.0654410933272436e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:37,392] Trial 29 finished with value: 0.6743615257048092 and parameters: {'var_smoothing': 3.9679607871181633e-07}. Best is trial 17 with value: 0.6743615257048092.
[I 2026-05-13 22:22:37,473] A new study created in memory with name: no-name-0b74fdab-2bed-4575-9a5c-376342d1c094
[I 2026-05-13 22:22:37,604] Trial 0 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.5134724182275519e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:37,721] Trial 1 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.3478177116802687e-11}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:37,848] Trial 2 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 5.601603817503298e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:37,947] Trial 3 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.5017995265951545e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,054] Trial 4 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.2642676064986629e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,162] Trial 5 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 4.4840877729077437e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,268] Trial 6 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.0549774340694088e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,365] Trial 7 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.2484030808286091e-08}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,465] Trial 8 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 3.149730300397852e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,568] Trial 9 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 2.158422082304072e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,669] Trial 10 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 2.6015182919619647e-07}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,770] Trial 11 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.176371971117909e-11}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,868] Trial 12 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.136550637943969e-11}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:38,971] Trial 13 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 5.052788775516901e-08}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,076] Trial 14 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 3.5417551256094504e-11}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,185] Trial 15 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 7.76849705676344e-07}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,277] Trial 16 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 7.653329043484054e-08}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,356] Trial 17 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.536210748557936e-08}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,490] Trial 18 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 7.552327523901134e-11}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,619] Trial 19 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 8.859563088414425e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,801] Trial 20 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 3.3532569923498766e-11}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:39,971] Trial 21 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 4.00178976768923e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,122] Trial 22 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 6.4628829329744215e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,252] Trial 23 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 4.077672338994071e-08}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,354] Trial 24 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 2.5075436446080494e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,482] Trial 25 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.6581847172247228e-07}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,619] Trial 26 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.2591926750626616e-08}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,722] Trial 27 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 7.091188450131106e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,834] Trial 28 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 1.6137722858757308e-10}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:40,982] Trial 29 finished with value: 0.7823149528067561 and parameters: {'var_smoothing': 2.6164613127923543e-09}. Best is trial 0 with value: 0.7823149528067561.
[I 2026-05-13 22:22:41,070] A new study created in memory with name: no-name-273d712e-7fd3-4aa5-8462-3ecf05c18503
[I 2026-05-13 22:22:41,210] Trial 0 finished with value: 0.7736265049697885 and parameters: {'var_smoothing': 5.675309007891892e-09}. Best is trial 0 with value: 0.7736265049697885.
[I 2026-05-13 22:22:41,358] Trial 1 finished with value: 0.7772447772447771 and parameters: {'var_smoothing': 3.473274541912229e-08}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,445] Trial 2 finished with value: 0.7700229013661849 and parameters: {'var_smoothing': 2.847893173431203e-10}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,517] Trial 3 finished with value: 0.7736265049697885 and parameters: {'var_smoothing': 3.582102641758181e-09}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,592] Trial 4 finished with value: 0.7612764550264549 and parameters: {'var_smoothing': 2.9156458542193306e-07}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,669] Trial 5 finished with value: 0.7612764550264549 and parameters: {'var_smoothing': 3.030159188749817e-07}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,746] Trial 6 finished with value: 0.7565207916615435 and parameters: {'var_smoothing': 4.245477585551382e-11}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,826] Trial 7 finished with value: 0.763096494439778 and parameters: {'var_smoothing': 1.0869620730769524e-10}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,906] Trial 8 finished with value: 0.7530089391593487 and parameters: {'var_smoothing': 1.8085728895942668e-11}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:41,985] Trial 9 finished with value: 0.7700229013661849 and parameters: {'var_smoothing': 1.5997393155444832e-09}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:42,069] Trial 10 finished with value: 0.7772447772447771 and parameters: {'var_smoothing': 2.905458801274833e-08}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:42,156] Trial 11 finished with value: 0.7772447772447771 and parameters: {'var_smoothing': 4.162889834833572e-08}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:42,246] Trial 12 finished with value: 0.7718146896229087 and parameters: {'var_smoothing': 5.226798625092416e-08}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:42,331] Trial 13 finished with value: 0.7772447772447771 and parameters: {'var_smoothing': 2.8987690123530284e-08}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:42,416] Trial 14 finished with value: 0.7736265049697885 and parameters: {'var_smoothing': 1.2552660697868793e-08}. Best is trial 1 with value: 0.7772447772447771.
[I 2026-05-13 22:22:42,500] Trial 15 finished with value: 0.7700229013661849 and parameters: {'var_smoothing': 7.690323006376458e-10}. Best is trial 1 with value: 0.7772447772447771.

done | Median MCC = 0.532
rnCV LDA ...

[I 2026-05-13 22:25:09,246] A new study created in memory with name: no-name-5d041328-f427-414b-8a77-13db853b6bef
[I 2026-05-13 22:25:09,353] Trial 0 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:09,453] Trial 1 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:09,544] Trial 2 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:09,640] Trial 3 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:09,743] Trial 4 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:09,851] Trial 5 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:09,961] Trial 6 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,093] Trial 7 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,206] Trial 8 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,318] Trial 9 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,445] Trial 10 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,558] Trial 11 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,658] Trial 12 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,734] Trial 13 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,815] Trial 14 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,899] Trial 15 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:10,989] Trial 16 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,078] Trial 17 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,170] Trial 18 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,260] Trial 19 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,350] Trial 20 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,437] Trial 21 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,526] Trial 22 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,610] Trial 23 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,693] Trial 24 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,783] Trial 25 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,881] Trial 26 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:11,962] Trial 27 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:12,050] Trial 28 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:12,154] Trial 29 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-13 22:25:12,214] A new study created in memory with name: no-name-0caf56e8-16e9-47de-82b3-6e6d4fcf2289
[I 2026-05-13 22:25:12,374] Trial 0 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:12,490] Trial 1 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:12,588] Trial 2 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:12,684] Trial 3 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:12,779] Trial 4 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:12,872] Trial 5 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:12,981] Trial 6 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,090] Trial 7 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,174] Trial 8 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,251] Trial 9 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,342] Trial 10 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,434] Trial 11 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,536] Trial 12 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,634] Trial 13 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,732] Trial 14 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,818] Trial 15 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:13,930] Trial 16 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,127] Trial 17 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,274] Trial 18 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,398] Trial 19 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,537] Trial 20 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,659] Trial 21 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,763] Trial 22 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,875] Trial 23 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:14,982] Trial 24 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:15,089] Trial 25 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:15,206] Trial 26 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:15,305] Trial 27 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:15,401] Trial 28 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:15,498] Trial 29 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-13 22:25:15,557] A new study created in memory with name: no-name-9d33ea4b-896d-43f1-811f-f261f0f88bfd
[I 2026-05-13 22:25:15,687] Trial 0 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:15,818] Trial 1 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:15,927] Trial 2 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,019] Trial 3 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,114] Trial 4 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,210] Trial 5 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,310] Trial 6 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,405] Trial 7 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,503] Trial 8 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,598] Trial 9 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,667] Trial 10 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,748] Trial 11 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,833] Trial 12 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:16,919] Trial 13 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,010] Trial 14 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,099] Trial 15 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,192] Trial 16 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,284] Trial 17 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,374] Trial 18 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,470] Trial 19 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,558] Trial 20 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,646] Trial 21 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,732] Trial 22 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,819] Trial 23 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,898] Trial 24 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:17,985] Trial 25 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:18,067] Trial 26 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:18,152] Trial 27 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:18,238] Trial 28 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:18,314] Trial 29 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-13 22:25:18,361] A new study created in memory with name: no-name-ac87d50e-439b-4802-aa60-4b32918958cb
[I 2026-05-13 22:25:18,440] Trial 0 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.7536531066585711.
[I 2026-05-13 22:25:18,517] Trial 1 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.7536531066585711.
[I 2026-05-13 22:25:18,597] Trial 2 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.7536531066585711.
[I 2026-05-13 22:25:18,675] Trial 3 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.7536531066585711.
[I 2026-05-13 22:25:18,753] Trial 4 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.7536531066585711.
[I 2026-05-13 22:25:18,833] Trial 5 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.7536531066585711.
[I 2026-05-13 22:25:18,930] Trial 6 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,015] Trial 7 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,093] Trial 8 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,172] Trial 9 finished with value: 0.7536531066585711 and parameters: {'shrinkage': None}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,258] Trial 10 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,344] Trial 11 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,431] Trial 12 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,519] Trial 13 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,605] Trial 14 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,693] Trial 15 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,782] Trial 16 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,870] Trial 17 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:19,959] Trial 18 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,041] Trial 19 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,129] Trial 20 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,215] Trial 21 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,305] Trial 22 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,390] Trial 23 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,476] Trial 24 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,562] Trial 25 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,646] Trial 26 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,731] Trial 27 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,815] Trial 28 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,900] Trial 29 finished with value: 0.7718528176155295 and parameters: {'shrinkage': 'auto'}. Best is trial 6 with value: 0.7718528176155295.
[I 2026-05-13 22:25:20,944] A new study created in memory with name: no-name-e0798285-8813-4c87-97dc-e941c46d78e1

done | Median MCC = 0.656
rnCV RandomForest ...

[I 2026-05-13 22:27:51,431] A new study created in memory with name: no-name-51aff1e1-1d5e-45ed-b6c2-b7c2a3e74f42
[I 2026-05-13 22:27:53,035] Trial 0 finished with value: 0.7793843583317267 and parameters: {'n_estimators': 297, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 0.7793843583317267.
[I 2026-05-13 22:27:56,063] Trial 1 finished with value: 0.7487519803903985 and parameters: {'n_estimators': 452, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 0.7793843583317267.
[I 2026-05-13 22:27:56,596] Trial 2 finished with value: 0.7515436099828113 and parameters: {'n_estimators': 82, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 0.7793843583317267.
[I 2026-05-13 22:27:58,938] Trial 3 finished with value: 0.7558023872679045 and parameters: {'n_estimators': 410, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 0.7793843583317267.
[I 2026-05-13 22:28:00,416] Trial 4 finished with value: 0.7804686193064322 and parameters: {'n_estimators': 285, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 4 with value: 0.7804686193064322.
[I 2026-05-13 22:28:02,131] Trial 5 finished with value: 0.7871250453176968 and parameters: {'n_estimators': 328, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:04,148] Trial 6 finished with value: 0.7453819734521488 and parameters: {'n_estimators': 364, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:05,497] Trial 7 finished with value: 0.7684758491210104 and parameters: {'n_estimators': 214, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:07,674] Trial 8 finished with value: 0.744923285586916 and parameters: {'n_estimators': 344, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:08,351] Trial 9 finished with value: 0.7781294380198824 and parameters: {'n_estimators': 112, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:09,436] Trial 10 finished with value: 0.7841880341880342 and parameters: {'n_estimators': 206, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:10,703] Trial 11 finished with value: 0.7841880341880342 and parameters: {'n_estimators': 208, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:11,776] Trial 12 finished with value: 0.7793501048218029 and parameters: {'n_estimators': 184, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:14,531] Trial 13 finished with value: 0.772727932320462 and parameters: {'n_estimators': 494, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:15,503] Trial 14 finished with value: 0.7841880341880342 and parameters: {'n_estimators': 156, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:16,952] Trial 15 finished with value: 0.7599074194999492 and parameters: {'n_estimators': 257, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:18,780] Trial 16 finished with value: 0.7793843583317267 and parameters: {'n_estimators': 348, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:19,101] Trial 17 finished with value: 0.7487708627493573 and parameters: {'n_estimators': 51, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:20,293] Trial 18 finished with value: 0.772727932320462 and parameters: {'n_estimators': 239, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:22,271] Trial 19 finished with value: 0.7793843583317267 and parameters: {'n_estimators': 320, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:24,011] Trial 20 finished with value: 0.764683688982101 and parameters: {'n_estimators': 396, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:24,776] Trial 21 finished with value: 0.7726936788105382 and parameters: {'n_estimators': 166, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:25,750] Trial 22 finished with value: 0.7841880341880342 and parameters: {'n_estimators': 218, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:26,412] Trial 23 finished with value: 0.7722072476789458 and parameters: {'n_estimators': 134, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:27,284] Trial 24 finished with value: 0.7793501048218029 and parameters: {'n_estimators': 195, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:28,515] Trial 25 finished with value: 0.764683688982101 and parameters: {'n_estimators': 259, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:29,867] Trial 26 finished with value: 0.7793843583317267 and parameters: {'n_estimators': 307, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:31,002] Trial 27 finished with value: 0.7694873648384085 and parameters: {'n_estimators': 234, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:32,328] Trial 28 finished with value: 0.7841880341880342 and parameters: {'n_estimators': 270, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:33,797] Trial 29 finished with value: 0.772727932320462 and parameters: {'n_estimators': 305, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.7871250453176968.
[I 2026-05-13 22:28:34,488] A new study created in memory with name: no-name-b8f46ba6-6516-4f6e-8233-767c93491d35
[I 2026-05-13 22:28:36,508] Trial 0 finished with value: 0.7096369855456249 and parameters: {'n_estimators': 238, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 0 with value: 0.7096369855456249.
[I 2026-05-13 22:28:38,236] Trial 1 finished with value: 0.7084897319119831 and parameters: {'n_estimators': 205, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 0 with value: 0.7096369855456249.
[I 2026-05-13 22:28:38,796] Trial 2 finished with value: 0.722394608211134 and parameters: {'n_estimators': 62, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 2 with value: 0.722394608211134.
[I 2026-05-13 22:28:41,411] Trial 3 finished with value: 0.734065228556754 and parameters: {'n_estimators': 486, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.734065228556754.
[I 2026-05-13 22:28:42,040] Trial 4 finished with value: 0.7465053438193184 and parameters: {'n_estimators': 126, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 4 with value: 0.7465053438193184.
[I 2026-05-13 22:28:43,029] Trial 5 finished with value: 0.75029374201788 and parameters: {'n_estimators': 192, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 5 with value: 0.75029374201788.
[I 2026-05-13 22:28:44,305] Trial 6 finished with value: 0.7323391812865497 and parameters: {'n_estimators': 176, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.75029374201788.
[I 2026-05-13 22:28:45,038] Trial 7 finished with value: 0.7326530612244898 and parameters: {'n_estimators': 108, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 5 with value: 0.75029374201788.
[I 2026-05-13 22:28:47,134] Trial 8 finished with value: 0.7057575757575757 and parameters: {'n_estimators': 308, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 5 with value: 0.75029374201788.
[I 2026-05-13 22:28:48,660] Trial 9 finished with value: 0.7577000871916756 and parameters: {'n_estimators': 236, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 9 with value: 0.7577000871916756.
[I 2026-05-13 22:28:51,071] Trial 10 finished with value: 0.7487215575885527 and parameters: {'n_estimators': 353, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 9 with value: 0.7577000871916756.
[I 2026-05-13 22:28:53,508] Trial 11 finished with value: 0.7577011494252873 and parameters: {'n_estimators': 367, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 11 with value: 0.7577011494252873.
[I 2026-05-13 22:28:55,754] Trial 12 finished with value: 0.7416636830170665 and parameters: {'n_estimators': 401, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 11 with value: 0.7577011494252873.
[I 2026-05-13 22:28:58,347] Trial 13 finished with value: 0.7465900383141763 and parameters: {'n_estimators': 417, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 11 with value: 0.7577011494252873.
[I 2026-05-13 22:29:00,115] Trial 14 finished with value: 0.7506432748538012 and parameters: {'n_estimators': 292, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 11 with value: 0.7577011494252873.
[I 2026-05-13 22:29:01,812] Trial 15 finished with value: 0.734256275609659 and parameters: {'n_estimators': 343, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 11 with value: 0.7577011494252873.
[I 2026-05-13 22:29:03,921] Trial 16 finished with value: 0.7397541472729442 and parameters: {'n_estimators': 473, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 11 with value: 0.7577011494252873.
[I 2026-05-13 22:29:05,252] Trial 17 finished with value: 0.7592707258341932 and parameters: {'n_estimators': 251, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:07,480] Trial 18 finished with value: 0.7368501714055252 and parameters: {'n_estimators': 419, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:09,256] Trial 19 finished with value: 0.7483444242790885 and parameters: {'n_estimators': 354, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:10,672] Trial 20 finished with value: 0.7471988795518207 and parameters: {'n_estimators': 266, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:12,374] Trial 21 finished with value: 0.7518633184267859 and parameters: {'n_estimators': 310, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:13,783] Trial 22 finished with value: 0.7433862433862434 and parameters: {'n_estimators': 250, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:15,165] Trial 23 finished with value: 0.7577011494252873 and parameters: {'n_estimators': 234, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:15,814] Trial 24 finished with value: 0.7577011494252873 and parameters: {'n_estimators': 130, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:18,616] Trial 25 finished with value: 0.7577011494252873 and parameters: {'n_estimators': 374, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:19,795] Trial 26 finished with value: 0.7410991268618389 and parameters: {'n_estimators': 167, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:21,730] Trial 27 finished with value: 0.7487215575885527 and parameters: {'n_estimators': 217, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:23,752] Trial 28 finished with value: 0.7057575757575757 and parameters: {'n_estimators': 280, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:25,497] Trial 29 finished with value: 0.7412865497076023 and parameters: {'n_estimators': 324, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 17 with value: 0.7592707258341932.
[I 2026-05-13 22:29:25,987] A new study created in memory with name: no-name-340339a6-872d-4d8b-b2dd-027a7f0ee64f
[I 2026-05-13 22:29:27,576] Trial 0 finished with value: 0.7502338332527012 and parameters: {'n_estimators': 246, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.7502338332527012.
[I 2026-05-13 22:29:29,559] Trial 1 finished with value: 0.7735794603719132 and parameters: {'n_estimators': 329, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.7735794603719132.
[I 2026-05-13 22:29:30,382] Trial 2 finished with value: 0.7884263418854612 and parameters: {'n_estimators': 133, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:30,954] Trial 3 finished with value: 0.7659694107062528 and parameters: {'n_estimators': 79, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:32,032] Trial 4 finished with value: 0.7694669062593591 and parameters: {'n_estimators': 149, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:33,639] Trial 5 finished with value: 0.7646520146520147 and parameters: {'n_estimators': 224, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:36,042] Trial 6 finished with value: 0.7735794603719132 and parameters: {'n_estimators': 451, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:38,619] Trial 7 finished with value: 0.7771945587238536 and parameters: {'n_estimators': 480, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:39,693] Trial 8 finished with value: 0.7751330430575715 and parameters: {'n_estimators': 161, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:40,813] Trial 9 finished with value: 0.7878200808625339 and parameters: {'n_estimators': 126, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:43,272] Trial 10 finished with value: 0.7167763157894737 and parameters: {'n_estimators': 362, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:43,775] Trial 11 finished with value: 0.7811715166553875 and parameters: {'n_estimators': 85, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:44,772] Trial 12 finished with value: 0.7113286275847853 and parameters: {'n_estimators': 168, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:45,155] Trial 13 finished with value: 0.7765061889355676 and parameters: {'n_estimators': 55, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:45,911] Trial 14 finished with value: 0.7782854126055879 and parameters: {'n_estimators': 133, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:47,160] Trial 15 finished with value: 0.7130904183535763 and parameters: {'n_estimators': 212, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:48,931] Trial 16 finished with value: 0.7663225663225663 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.
[I 2026-05-13 22:29:49,587] Trial 17 finished with value: 0.7817401840390347 and parameters: {'n_estimators': 112, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 2 with value: 0.7884263418854612.

done | Median MCC = 0.592
rnCV LightGBM ...

[I 2026-05-13 23:08:37,431] A new study created in memory with name: no-name-4121a580-29ad-42d6-a342-be5329e5c02b
[I 2026-05-13 23:08:37,619] Trial 0 finished with value: 0.7996700690792865 and parameters: {'n_estimators': 187, 'max_depth': 7, 'learning_rate': 0.07768811685516967, 'num_leaves': 41, 'reg_alpha': 0.04950159553733195, 'reg_lambda': 0.3833332156156664}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:37,772] Trial 1 finished with value: 0.7811414392059554 and parameters: {'n_estimators': 159, 'max_depth': 8, 'learning_rate': 0.2651225974297431, 'num_leaves': 33, 'reg_alpha': 1.4685885989200866, 'reg_lambda': 0.13049073550362397}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:37,947] Trial 2 finished with value: 0.7745294537747368 and parameters: {'n_estimators': 192, 'max_depth': 8, 'learning_rate': 0.012732945242475176, 'num_leaves': 19, 'reg_alpha': 0.001204685241203032, 'reg_lambda': 2.1403233140986067}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:38,138] Trial 3 finished with value: 0.7652335292298176 and parameters: {'n_estimators': 245, 'max_depth': 8, 'learning_rate': 0.27895744302956854, 'num_leaves': 54, 'reg_alpha': 0.07013219779945795, 'reg_lambda': 1.3246974647468452}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:38,279] Trial 4 finished with value: 0.7664852104363759 and parameters: {'n_estimators': 79, 'max_depth': 6, 'learning_rate': 0.01628359108363256, 'num_leaves': 61, 'reg_alpha': 0.12229065947034364, 'reg_lambda': 0.045566719139214756}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:38,434] Trial 5 finished with value: 0.7788425886312428 and parameters: {'n_estimators': 116, 'max_depth': 7, 'learning_rate': 0.047183412869566586, 'num_leaves': 42, 'reg_alpha': 0.001188937983177301, 'reg_lambda': 0.2954894558726685}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:38,603] Trial 6 finished with value: 0.7860280724311582 and parameters: {'n_estimators': 203, 'max_depth': 6, 'learning_rate': 0.247759517096838, 'num_leaves': 48, 'reg_alpha': 0.02741773675242096, 'reg_lambda': 0.05599223654063348}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:38,764] Trial 7 finished with value: 0.7861409796893667 and parameters: {'n_estimators': 225, 'max_depth': 3, 'learning_rate': 0.09658179826892162, 'num_leaves': 47, 'reg_alpha': 0.0069427294924301495, 'reg_lambda': 0.0032787264983352763}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:38,901] Trial 8 finished with value: 0.7300584795321637 and parameters: {'n_estimators': 129, 'max_depth': 5, 'learning_rate': 0.06954241509602922, 'num_leaves': 36, 'reg_alpha': 8.984529773922551, 'reg_lambda': 0.0025596420901526653}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:39,052] Trial 9 finished with value: 0.795917623473665 and parameters: {'n_estimators': 102, 'max_depth': 3, 'learning_rate': 0.0921977216689866, 'num_leaves': 27, 'reg_alpha': 0.07332348382056163, 'reg_lambda': 0.009499535455183799}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:39,252] Trial 10 finished with value: 0.7713401149933657 and parameters: {'n_estimators': 286, 'max_depth': 5, 'learning_rate': 0.02854352081866998, 'num_leaves': 15, 'reg_alpha': 0.5593703617138849, 'reg_lambda': 8.210101727880163}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:39,395] Trial 11 finished with value: 0.7829639287266406 and parameters: {'n_estimators': 63, 'max_depth': 3, 'learning_rate': 0.11129393676818743, 'num_leaves': 23, 'reg_alpha': 0.01334735339239911, 'reg_lambda': 0.009063362793047888}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:39,577] Trial 12 finished with value: 0.7888487542835975 and parameters: {'n_estimators': 152, 'max_depth': 4, 'learning_rate': 0.1351551450891584, 'num_leaves': 28, 'reg_alpha': 0.25603659963439934, 'reg_lambda': 0.014412344836007852}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:39,731] Trial 13 finished with value: 0.7721441927207896 and parameters: {'n_estimators': 102, 'max_depth': 7, 'learning_rate': 0.040617802618805925, 'num_leaves': 28, 'reg_alpha': 0.03125352114176432, 'reg_lambda': 0.0010160308028997085}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:39,919] Trial 14 finished with value: 0.765192398728613 and parameters: {'n_estimators': 169, 'max_depth': 4, 'learning_rate': 0.154815384291306, 'num_leaves': 41, 'reg_alpha': 0.005325861130447371, 'reg_lambda': 0.4029540279836746}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:40,121] Trial 15 finished with value: 0.7781963360056666 and parameters: {'n_estimators': 249, 'max_depth': 7, 'learning_rate': 0.07372962878676767, 'num_leaves': 30, 'reg_alpha': 0.8817657413527484, 'reg_lambda': 0.018500586988987072}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:40,284] Trial 16 finished with value: 0.7629813436265049 and parameters: {'n_estimators': 92, 'max_depth': 4, 'learning_rate': 0.02767378415387765, 'num_leaves': 24, 'reg_alpha': 0.10231663179231058, 'reg_lambda': 0.7304985400004865}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:40,443] Trial 17 finished with value: 0.7825842901403317 and parameters: {'n_estimators': 50, 'max_depth': 6, 'learning_rate': 0.17422902047674646, 'num_leaves': 37, 'reg_alpha': 0.28979655633856627, 'reg_lambda': 0.13134459997759748}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:40,618] Trial 18 finished with value: 0.7596286313267445 and parameters: {'n_estimators': 136, 'max_depth': 5, 'learning_rate': 0.07160910131356839, 'num_leaves': 47, 'reg_alpha': 2.8196899638594504, 'reg_lambda': 5.087738873168151}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:40,814] Trial 19 finished with value: 0.7707983452928818 and parameters: {'n_estimators': 199, 'max_depth': 7, 'learning_rate': 0.037521028691439896, 'num_leaves': 57, 'reg_alpha': 0.036876080596865875, 'reg_lambda': 0.00642527737667766}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:41,010] Trial 20 finished with value: 0.7961124896608768 and parameters: {'n_estimators': 280, 'max_depth': 3, 'learning_rate': 0.09235625271893141, 'num_leaves': 33, 'reg_alpha': 0.004049577753458184, 'reg_lambda': 0.04627985463064878}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:41,225] Trial 21 finished with value: 0.7719319251402705 and parameters: {'n_estimators': 294, 'max_depth': 3, 'learning_rate': 0.093049734722478, 'num_leaves': 33, 'reg_alpha': 0.0034439474769324113, 'reg_lambda': 0.034631039266834585}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:41,500] Trial 22 finished with value: 0.7903996571306119 and parameters: {'n_estimators': 262, 'max_depth': 4, 'learning_rate': 0.05714349766823148, 'num_leaves': 43, 'reg_alpha': 0.012292928122072206, 'reg_lambda': 0.2173933766388549}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:41,723] Trial 23 finished with value: 0.7572098152743315 and parameters: {'n_estimators': 230, 'max_depth': 3, 'learning_rate': 0.11815049218908344, 'num_leaves': 24, 'reg_alpha': 0.002748749621017905, 'reg_lambda': 0.02470800112257635}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:41,939] Trial 24 finished with value: 0.7928551533470193 and parameters: {'n_estimators': 268, 'max_depth': 3, 'learning_rate': 0.1731698251684717, 'num_leaves': 33, 'reg_alpha': 0.014133326490601023, 'reg_lambda': 0.07574375072391944}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:42,140] Trial 25 finished with value: 0.7793894302754817 and parameters: {'n_estimators': 216, 'max_depth': 4, 'learning_rate': 0.08466105286412769, 'num_leaves': 38, 'reg_alpha': 0.19915515486125096, 'reg_lambda': 0.6048651215748555}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:42,324] Trial 26 finished with value: 0.7856612132172548 and parameters: {'n_estimators': 187, 'max_depth': 5, 'learning_rate': 0.05944298067464479, 'num_leaves': 51, 'reg_alpha': 0.054555855363413085, 'reg_lambda': 0.005418226596689585}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:42,491] Trial 27 finished with value: 0.7676884518989783 and parameters: {'n_estimators': 140, 'max_depth': 3, 'learning_rate': 0.03332744327872652, 'num_leaves': 30, 'reg_alpha': 0.019095375194993706, 'reg_lambda': 0.13727423350171244}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:42,671] Trial 28 finished with value: 0.7948053773480718 and parameters: {'n_estimators': 112, 'max_depth': 6, 'learning_rate': 0.2106999124283938, 'num_leaves': 20, 'reg_alpha': 0.006957313816002768, 'reg_lambda': 0.011153458013320783}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:42,866] Trial 29 finished with value: 0.7696811385335974 and parameters: {'n_estimators': 172, 'max_depth': 4, 'learning_rate': 0.020801029014700646, 'num_leaves': 34, 'reg_alpha': 0.0021627858085200642, 'reg_lambda': 0.0015582768704998085}. Best is trial 0 with value: 0.7996700690792865.
[I 2026-05-13 23:08:42,959] A new study created in memory with name: no-name-4e0127d1-3858-45d0-8dc9-6cc1d9770630
[I 2026-05-13 23:08:43,140] Trial 0 finished with value: 0.7339766081871346 and parameters: {'n_estimators': 154, 'max_depth': 7, 'learning_rate': 0.010003890870040017, 'num_leaves': 29, 'reg_alpha': 0.00386387940515873, 'reg_lambda': 0.0023407464805767528}. Best is trial 0 with value: 0.7339766081871346.
[I 2026-05-13 23:08:43,296] Trial 1 finished with value: 0.7709206246226764 and parameters: {'n_estimators': 96, 'max_depth': 5, 'learning_rate': 0.03855437519010386, 'num_leaves': 41, 'reg_alpha': 0.047509237210306136, 'reg_lambda': 0.5506529897945993}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:43,438] Trial 2 finished with value: 0.6876949160637104 and parameters: {'n_estimators': 101, 'max_depth': 8, 'learning_rate': 0.010976270367293662, 'num_leaves': 47, 'reg_alpha': 0.046689498537088946, 'reg_lambda': 0.1716956585247387}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:43,577] Trial 3 finished with value: 0.723391812865497 and parameters: {'n_estimators': 85, 'max_depth': 4, 'learning_rate': 0.15233399158649277, 'num_leaves': 62, 'reg_alpha': 0.017934807211789795, 'reg_lambda': 0.5878824056644089}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:43,755] Trial 4 finished with value: 0.756480558325025 and parameters: {'n_estimators': 269, 'max_depth': 8, 'learning_rate': 0.013354284130669362, 'num_leaves': 16, 'reg_alpha': 0.0047788310658577, 'reg_lambda': 3.25514256249193}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:43,885] Trial 5 finished with value: 0.7076431764956355 and parameters: {'n_estimators': 74, 'max_depth': 5, 'learning_rate': 0.2599674562373734, 'num_leaves': 41, 'reg_alpha': 0.5854751355295726, 'reg_lambda': 0.018283634209844524}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:44,044] Trial 6 finished with value: 0.6954523463957427 and parameters: {'n_estimators': 222, 'max_depth': 8, 'learning_rate': 0.010641773304807034, 'num_leaves': 51, 'reg_alpha': 9.024940671927414, 'reg_lambda': 0.9832469717408685}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:44,194] Trial 7 finished with value: 0.7044405147853423 and parameters: {'n_estimators': 120, 'max_depth': 7, 'learning_rate': 0.014206180498459313, 'num_leaves': 36, 'reg_alpha': 4.3090547518743145, 'reg_lambda': 0.014943646773788368}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:44,340] Trial 8 finished with value: 0.7031270148291425 and parameters: {'n_estimators': 122, 'max_depth': 3, 'learning_rate': 0.01068088760747994, 'num_leaves': 48, 'reg_alpha': 0.0070228349857643394, 'reg_lambda': 0.011539490593862677}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:44,507] Trial 9 finished with value: 0.7482859447469248 and parameters: {'n_estimators': 173, 'max_depth': 3, 'learning_rate': 0.07047601150388612, 'num_leaves': 22, 'reg_alpha': 0.22762614721505595, 'reg_lambda': 0.6295546558422283}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:44,648] Trial 10 finished with value: 0.7078408195429472 and parameters: {'n_estimators': 53, 'max_depth': 5, 'learning_rate': 0.037954166022949244, 'num_leaves': 63, 'reg_alpha': 0.0011616605018495319, 'reg_lambda': 7.8262404713080755}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:44,853] Trial 11 finished with value: 0.7681000209248797 and parameters: {'n_estimators': 260, 'max_depth': 6, 'learning_rate': 0.029902741525435754, 'num_leaves': 15, 'reg_alpha': 0.05846933757194527, 'reg_lambda': 6.925530031488983}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:45,072] Trial 12 finished with value: 0.7681000209248797 and parameters: {'n_estimators': 294, 'max_depth': 6, 'learning_rate': 0.031095056907767236, 'num_leaves': 30, 'reg_alpha': 0.10103724639796727, 'reg_lambda': 9.531887538752523}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:45,264] Trial 13 finished with value: 0.7519556714471968 and parameters: {'n_estimators': 213, 'max_depth': 6, 'learning_rate': 0.02429762706948246, 'num_leaves': 38, 'reg_alpha': 0.9343436929898182, 'reg_lambda': 2.1664689521969533}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:45,463] Trial 14 finished with value: 0.703968253968254 and parameters: {'n_estimators': 219, 'max_depth': 4, 'learning_rate': 0.07403355204589786, 'num_leaves': 17, 'reg_alpha': 0.0428356302783664, 'reg_lambda': 0.08156392396851267}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:45,660] Trial 15 finished with value: 0.7586279051309249 and parameters: {'n_estimators': 240, 'max_depth': 5, 'learning_rate': 0.022043247547984892, 'num_leaves': 26, 'reg_alpha': 0.18195409681578875, 'reg_lambda': 0.20126700934719646}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:45,817] Trial 16 finished with value: 0.763303533418476 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.05177043585597724, 'num_leaves': 54, 'reg_alpha': 0.03385151533247169, 'reg_lambda': 2.1215209792361183}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:45,984] Trial 17 finished with value: 0.7246780744965863 and parameters: {'n_estimators': 192, 'max_depth': 4, 'learning_rate': 0.10489893877383473, 'num_leaves': 43, 'reg_alpha': 0.8138053528329302, 'reg_lambda': 0.0397258382534585}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:46,172] Trial 18 finished with value: 0.6932980599647266 and parameters: {'n_estimators': 256, 'max_depth': 6, 'learning_rate': 0.04366117791575047, 'num_leaves': 33, 'reg_alpha': 0.014245615552310223, 'reg_lambda': 0.0010435998821835084}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:46,364] Trial 19 finished with value: 0.736200542444967 and parameters: {'n_estimators': 298, 'max_depth': 7, 'learning_rate': 0.020334117075579212, 'num_leaves': 56, 'reg_alpha': 0.0011018530398829106, 'reg_lambda': 0.32444319203848526}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:46,524] Trial 20 finished with value: 0.7491877842755036 and parameters: {'n_estimators': 182, 'max_depth': 5, 'learning_rate': 0.06832347309050196, 'num_leaves': 23, 'reg_alpha': 0.31787145521840793, 'reg_lambda': 1.2424488750125033}. Best is trial 1 with value: 0.7709206246226764.
[I 2026-05-13 23:08:46,716] Trial 21 finished with value: 0.7779870265745972 and parameters: {'n_estimators': 292, 'max_depth': 6, 'learning_rate': 0.03422062407235996, 'num_leaves': 32, 'reg_alpha': 0.12234402865739066, 'reg_lambda': 6.490449672549841}. Best is trial 21 with value: 0.7779870265745972.
[I 2026-05-13 23:08:46,915] Trial 22 finished with value: 0.7832810867293626 and parameters: {'n_estimators': 270, 'max_depth': 7, 'learning_rate': 0.03092859453354373, 'num_leaves': 34, 'reg_alpha': 0.09502718431431569, 'reg_lambda': 4.2629659420311565}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:47,153] Trial 23 finished with value: 0.7679415652797382 and parameters: {'n_estimators': 280, 'max_depth': 7, 'learning_rate': 0.036353016447655095, 'num_leaves': 32, 'reg_alpha': 0.12874295798258642, 'reg_lambda': 3.7863745122346066}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:47,346] Trial 24 finished with value: 0.7496619337390129 and parameters: {'n_estimators': 235, 'max_depth': 7, 'learning_rate': 0.017139590111821822, 'num_leaves': 36, 'reg_alpha': 1.9570431828895196, 'reg_lambda': 4.570278106745487}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:47,547] Trial 25 finished with value: 0.7317460317460318 and parameters: {'n_estimators': 277, 'max_depth': 5, 'learning_rate': 0.05224127221535926, 'num_leaves': 44, 'reg_alpha': 0.018436632963783898, 'reg_lambda': 1.3192120519231012}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:47,745] Trial 26 finished with value: 0.7608836907082521 and parameters: {'n_estimators': 249, 'max_depth': 6, 'learning_rate': 0.0275179275571123, 'num_leaves': 40, 'reg_alpha': 0.35107824745254174, 'reg_lambda': 0.45675655659866127}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:47,919] Trial 27 finished with value: 0.7674900928902578 and parameters: {'n_estimators': 134, 'max_depth': 4, 'learning_rate': 0.04188579424359883, 'num_leaves': 34, 'reg_alpha': 0.09492213764874252, 'reg_lambda': 2.177266389010157}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:48,110] Trial 28 finished with value: 0.7309098005819318 and parameters: {'n_estimators': 202, 'max_depth': 7, 'learning_rate': 0.09733018129159521, 'num_leaves': 28, 'reg_alpha': 0.08962932089924629, 'reg_lambda': 0.07676487920542581}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:48,266] Trial 29 finished with value: 0.7476015350175887 and parameters: {'n_estimators': 156, 'max_depth': 7, 'learning_rate': 0.018119344283404466, 'num_leaves': 26, 'reg_alpha': 0.010106211682763088, 'reg_lambda': 0.005595622754225747}. Best is trial 22 with value: 0.7832810867293626.
[I 2026-05-13 23:08:48,360] A new study created in memory with name: no-name-7b7d0135-62a3-490d-a57e-b4099ae348bb
[I 2026-05-13 23:08:48,508] Trial 0 finished with value: 0.7208311053395463 and parameters: {'n_estimators': 159, 'max_depth': 3, 'learning_rate': 0.06485121677838487, 'num_leaves': 36, 'reg_alpha': 0.04802542406217437, 'reg_lambda': 0.020957490791939464}. Best is trial 0 with value: 0.7208311053395463.
[I 2026-05-13 23:08:48,636] Trial 1 finished with value: 0.7600041467965997 and parameters: {'n_estimators': 101, 'max_depth': 6, 'learning_rate': 0.027709346761734664, 'num_leaves': 28, 'reg_alpha': 0.30516542796987534, 'reg_lambda': 0.13078814409401443}. Best is trial 1 with value: 0.7600041467965997.
[I 2026-05-13 23:08:48,769] Trial 2 finished with value: 0.7332911659287372 and parameters: {'n_estimators': 83, 'max_depth': 6, 'learning_rate': 0.018725785562119596, 'num_leaves': 53, 'reg_alpha': 2.60556055283209, 'reg_lambda': 0.0948303491420347}. Best is trial 1 with value: 0.7600041467965997.
[I 2026-05-13 23:08:48,947] Trial 3 finished with value: 0.7403414195867025 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.05575832752388716, 'num_leaves': 18, 'reg_alpha': 0.05158094689171093, 'reg_lambda': 0.002432896662591013}. Best is trial 1 with value: 0.7600041467965997.

done | Median MCC = 0.606
rnCV XGBoost ...

[I 2026-05-13 23:12:55,100] A new study created in memory with name: no-name-75654608-abdf-495d-98af-d7b86433c6da
[I 2026-05-13 23:12:56,685] Trial 0 finished with value: 0.776661502946358 and parameters: {'n_estimators': 187, 'max_depth': 7, 'learning_rate': 0.07768811685516967, 'subsample': 0.8179532731987588, 'colsample_bytree': 0.7694619197355619, 'reg_alpha': 0.3833332156156664, 'reg_lambda': 0.0562793204741517}. Best is trial 0 with value: 0.776661502946358.
[I 2026-05-13 23:12:58,380] Trial 1 finished with value: 0.7474069197571501 and parameters: {'n_estimators': 273, 'max_depth': 8, 'learning_rate': 0.036845938035010996, 'subsample': 0.9166900152330658, 'colsample_bytree': 0.8115579679011617, 'reg_alpha': 0.18714500686240676, 'reg_lambda': 5.039489598671215}. Best is trial 0 with value: 0.776661502946358.
[I 2026-05-13 23:12:58,619] Trial 2 finished with value: 0.6552929828791898 and parameters: {'n_estimators': 67, 'max_depth': 3, 'learning_rate': 0.010711863369746433, 'subsample': 0.9330479382191752, 'colsample_bytree': 0.9112627003799402, 'reg_alpha': 3.0202896401586674, 'reg_lambda': 8.212461922256873}. Best is trial 0 with value: 0.776661502946358.
[I 2026-05-13 23:12:59,089] Trial 3 finished with value: 0.7791954022988504 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.1422119973969722, 'subsample': 0.6473097703475733, 'colsample_bytree': 0.8559684085310095, 'reg_alpha': 0.003744666535741566, 'reg_lambda': 6.007249475906204}. Best is trial 3 with value: 0.7791954022988504.
[I 2026-05-13 23:12:59,987] Trial 4 finished with value: 0.7599233716475094 and parameters: {'n_estimators': 180, 'max_depth': 5, 'learning_rate': 0.024591256383397347, 'subsample': 0.9096934757736866, 'colsample_bytree': 0.7824601328866194, 'reg_alpha': 0.1878173875716192, 'reg_lambda': 0.001188937983177301}. Best is trial 3 with value: 0.7791954022988504.
[I 2026-05-13 23:13:00,834] Trial 5 finished with value: 0.7554462659380693 and parameters: {'n_estimators': 205, 'max_depth': 6, 'learning_rate': 0.0815241575370242, 'subsample': 0.9774992314058497, 'colsample_bytree': 0.8727281196413934, 'reg_alpha': 0.02741773675242096, 'reg_lambda': 0.05599223654063348}. Best is trial 3 with value: 0.7791954022988504.
[I 2026-05-13 23:13:01,244] Trial 6 finished with value: 0.7784880279795535 and parameters: {'n_estimators': 225, 'max_depth': 3, 'learning_rate': 0.09658179826892162, 'subsample': 0.8682551478472638, 'colsample_bytree': 0.6841530244295364, 'reg_alpha': 0.0032787264983352763, 'reg_lambda': 0.01826894228153233}. Best is trial 3 with value: 0.7791954022988504.
[I 2026-05-13 23:13:01,614] Trial 7 finished with value: 0.7769230769230769 and parameters: {'n_estimators': 141, 'max_depth': 6, 'learning_rate': 0.044449575514094085, 'subsample': 0.9953495352236905, 'colsample_bytree': 0.6408179242992113, 'reg_alpha': 0.006847105576684045, 'reg_lambda': 0.004418125737902547}. Best is trial 3 with value: 0.7791954022988504.
[I 2026-05-13 23:13:02,663] Trial 8 finished with value: 0.7761865190285527 and parameters: {'n_estimators': 213, 'max_depth': 4, 'learning_rate': 0.04884246274247253, 'subsample': 0.6977702368006411, 'colsample_bytree': 0.6635878334582078, 'reg_alpha': 0.0027637615125314257, 'reg_lambda': 0.4220057397195018}. Best is trial 3 with value: 0.7791954022988504.
[I 2026-05-13 23:13:03,156] Trial 9 finished with value: 0.7845502645502647 and parameters: {'n_estimators': 84, 'max_depth': 4, 'learning_rate': 0.035047075708368194, 'subsample': 0.9283972919391741, 'colsample_bytree': 0.6388405103172244, 'reg_alpha': 2.2479136784899816, 'reg_lambda': 0.002423224390060893}. Best is trial 9 with value: 0.7845502645502647.
[I 2026-05-13 23:13:03,390] Trial 10 finished with value: 0.7874779541446207 and parameters: {'n_estimators': 55, 'max_depth': 4, 'learning_rate': 0.25548712554966907, 'subsample': 0.7274015140552499, 'colsample_bytree': 0.9797120575762088, 'reg_alpha': 8.986065061047563, 'reg_lambda': 0.001550143405078222}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:03,706] Trial 11 finished with value: 0.7703703703703703 and parameters: {'n_estimators': 70, 'max_depth': 4, 'learning_rate': 0.29385913904039873, 'subsample': 0.7416172130864247, 'colsample_bytree': 0.9915948546594284, 'reg_alpha': 9.927946948569376, 'reg_lambda': 0.0013819682007973732}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:04,254] Trial 12 finished with value: 0.7850793650793652 and parameters: {'n_estimators': 118, 'max_depth': 4, 'learning_rate': 0.2745515589440244, 'subsample': 0.7973783881112185, 'colsample_bytree': 0.9682869093773956, 'reg_alpha': 1.3475001443746808, 'reg_lambda': 0.008222738054120835}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:04,855] Trial 13 finished with value: 0.7738692050061696 and parameters: {'n_estimators': 119, 'max_depth': 4, 'learning_rate': 0.28514496226255664, 'subsample': 0.778841597568426, 'colsample_bytree': 0.9909035696905898, 'reg_alpha': 1.1195220044779206, 'reg_lambda': 0.009579469852958414}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:05,336] Trial 14 finished with value: 0.7610136452241715 and parameters: {'n_estimators': 118, 'max_depth': 3, 'learning_rate': 0.1705806653318773, 'subsample': 0.644554467027903, 'colsample_bytree': 0.933949108979414, 'reg_alpha': 9.678496487969038, 'reg_lambda': 0.010821645389847073}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:05,645] Trial 15 finished with value: 0.7868894458368142 and parameters: {'n_estimators': 51, 'max_depth': 5, 'learning_rate': 0.17415230997435205, 'subsample': 0.7175491733881159, 'colsample_bytree': 0.9433702322654506, 'reg_alpha': 0.8626441457475996, 'reg_lambda': 0.25350591658331173}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:05,978] Trial 16 finished with value: 0.7717460317460318 and parameters: {'n_estimators': 50, 'max_depth': 5, 'learning_rate': 0.15664528613274836, 'subsample': 0.7140327153705466, 'colsample_bytree': 0.9180624202266856, 'reg_alpha': 0.05032864686595619, 'reg_lambda': 0.4381166822403548}. Best is trial 10 with value: 0.7874779541446207.
[I 2026-05-13 23:13:06,232] Trial 17 finished with value: 0.7916631014517556 and parameters: {'n_estimators': 93, 'max_depth': 6, 'learning_rate': 0.19940600438370193, 'subsample': 0.6795071651945637, 'colsample_bytree': 0.8556462555507698, 'reg_alpha': 0.6842727502308474, 'reg_lambda': 0.40137682611810344}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:06,490] Trial 18 finished with value: 0.7825396825396825 and parameters: {'n_estimators': 96, 'max_depth': 7, 'learning_rate': 0.10686737329138916, 'subsample': 0.6096446403202956, 'colsample_bytree': 0.7185367153204425, 'reg_alpha': 4.5092717701629494, 'reg_lambda': 1.4978919187102921}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:06,906] Trial 19 finished with value: 0.7904172099087354 and parameters: {'n_estimators': 152, 'max_depth': 7, 'learning_rate': 0.2177593152553132, 'subsample': 0.6718599298091174, 'colsample_bytree': 0.8638607871845779, 'reg_alpha': 0.5037104714659906, 'reg_lambda': 0.14199091005443198}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:08,037] Trial 20 finished with value: 0.7570420748109425 and parameters: {'n_estimators': 155, 'max_depth': 8, 'learning_rate': 0.020340760252111914, 'subsample': 0.6679088961221273, 'colsample_bytree': 0.8513167455175135, 'reg_alpha': 0.02906135569061934, 'reg_lambda': 0.16357533116129785}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:08,675] Trial 21 finished with value: 0.7825842901403317 and parameters: {'n_estimators': 93, 'max_depth': 7, 'learning_rate': 0.212645176970214, 'subsample': 0.7570907451088866, 'colsample_bytree': 0.8158227117306985, 'reg_alpha': 0.4768656043130094, 'reg_lambda': 1.0504858704099402}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:09,172] Trial 22 finished with value: 0.7811111111111112 and parameters: {'n_estimators': 153, 'max_depth': 6, 'learning_rate': 0.12171804341381684, 'subsample': 0.6797785928545985, 'colsample_bytree': 0.8866923383373194, 'reg_alpha': 0.14297972314836518, 'reg_lambda': 0.04608728469106707}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:10,751] Trial 23 finished with value: 0.7656284153005464 and parameters: {'n_estimators': 135, 'max_depth': 7, 'learning_rate': 0.22288327847551515, 'subsample': 0.6382578976994979, 'colsample_bytree': 0.8355665703336634, 'reg_alpha': 0.47348805939441535, 'reg_lambda': 1.696031253417138}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:11,048] Trial 24 finished with value: 0.7870370370370371 and parameters: {'n_estimators': 96, 'max_depth': 6, 'learning_rate': 0.2101133206005816, 'subsample': 0.7336075163025929, 'colsample_bytree': 0.7210755068321661, 'reg_alpha': 5.118559758887645, 'reg_lambda': 0.10840700180748782}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:11,539] Trial 25 finished with value: 0.7817460317460317 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.07629111797812245, 'subsample': 0.6087213046661282, 'colsample_bytree': 0.8900930686857119, 'reg_alpha': 0.06911000683740776, 'reg_lambda': 0.02217905968202545}. Best is trial 17 with value: 0.7916631014517556.
[I 2026-05-13 23:13:12,107] Trial 26 finished with value: 0.7950928381962864 and parameters: {'n_estimators': 76, 'max_depth': 7, 'learning_rate': 0.12646387198504572, 'subsample': 0.6856722377454113, 'colsample_bytree': 0.7499663372084805, 'reg_alpha': 1.586346348483586, 'reg_lambda': 0.6640050845856017}. Best is trial 26 with value: 0.7950928381962864.
[I 2026-05-13 23:13:12,982] Trial 27 finished with value: 0.7806346644119041 and parameters: {'n_estimators': 164, 'max_depth': 7, 'learning_rate': 0.1292430953002442, 'subsample': 0.834575561362342, 'colsample_bytree': 0.7449399061173859, 'reg_alpha': 1.8894526576355728, 'reg_lambda': 0.7756689503170722}. Best is trial 26 with value: 0.7950928381962864.
[I 2026-05-13 23:13:13,429] Trial 28 finished with value: 0.7757656655543196 and parameters: {'n_estimators': 107, 'max_depth': 7, 'learning_rate': 0.06498639069727266, 'subsample': 0.6776008504308373, 'colsample_bytree': 0.7717421255650345, 'reg_alpha': 0.638832750281892, 'reg_lambda': 2.109064442126427}. Best is trial 26 with value: 0.7950928381962864.
[I 2026-05-13 23:13:13,752] Trial 29 finished with value: 0.772727932320462 and parameters: {'n_estimators': 76, 'max_depth': 7, 'learning_rate': 0.18385805323737664, 'subsample': 0.7612752053042023, 'colsample_bytree': 0.7518003464607828, 'reg_alpha': 0.0011031172180585912, 'reg_lambda': 0.2310954694585098}. Best is trial 26 with value: 0.7950928381962864.
[I 2026-05-13 23:13:13,876] A new study created in memory with name: no-name-fd100c5d-9aa4-4461-9e44-c377029ad2f1
[I 2026-05-13 23:13:14,546] Trial 0 finished with value: 0.7339766081871345 and parameters: {'n_estimators': 154, 'max_depth': 7, 'learning_rate': 0.010003890870040017, 'subsample': 0.7209330290527359, 'colsample_bytree': 0.6587023563268452, 'reg_alpha': 0.0023407464805767528, 'reg_lambda': 0.005559565426712569}. Best is trial 0 with value: 0.7339766081871345.
[I 2026-05-13 23:13:15,724] Trial 1 finished with value: 0.7444549068842855 and parameters: {'n_estimators': 136, 'max_depth': 5, 'learning_rate': 0.06250253762274369, 'subsample': 0.7676778057613179, 'colsample_bytree': 0.8740878001587038, 'reg_alpha': 0.0065736866551383355, 'reg_lambda': 3.254391115088489}. Best is trial 1 with value: 0.7444549068842855.
[I 2026-05-13 23:13:16,012] Trial 2 finished with value: 0.7480106100795756 and parameters: {'n_estimators': 56, 'max_depth': 7, 'learning_rate': 0.04134374308918326, 'subsample': 0.8234759313783007, 'colsample_bytree': 0.6561547754380935, 'reg_alpha': 0.006200203677164719, 'reg_lambda': 1.5957993164212976}. Best is trial 2 with value: 0.7480106100795756.
[I 2026-05-13 23:13:16,796] Trial 3 finished with value: 0.7299154655476494 and parameters: {'n_estimators': 293, 'max_depth': 4, 'learning_rate': 0.1053524041590806, 'subsample': 0.9505556609184154, 'colsample_bytree': 0.957842665401539, 'reg_alpha': 0.0021886526657465457, 'reg_lambda': 0.0014329107238467847}. Best is trial 2 with value: 0.7480106100795756.
[I 2026-05-13 23:13:18,367] Trial 4 finished with value: 0.6910749780856081 and parameters: {'n_estimators': 92, 'max_depth': 8, 'learning_rate': 0.013972373892609564, 'subsample': 0.7684430500020208, 'colsample_bytree': 0.9831558120602008, 'reg_alpha': 0.13572540301313674, 'reg_lambda': 0.5854751355295726}. Best is trial 2 with value: 0.7480106100795756.
[I 2026-05-13 23:13:18,619] Trial 5 finished with value: 0.6868610692140105 and parameters: {'n_estimators': 129, 'max_depth': 7, 'learning_rate': 0.1709398504585972, 'subsample': 0.6073153109376767, 'colsample_bytree': 0.9000577259779869, 'reg_alpha': 9.024940671927414, 'reg_lambda': 0.9832469717408685}. Best is trial 2 with value: 0.7480106100795756.
[I 2026-05-13 23:13:18,994] Trial 6 finished with value: 0.7208161014612627 and parameters: {'n_estimators': 120, 'max_depth': 7, 'learning_rate': 0.014206180498459313, 'subsample': 0.779157410470362, 'colsample_bytree': 0.9634382012372382, 'reg_alpha': 0.014943646773788368, 'reg_lambda': 0.014161242322273672}. Best is trial 2 with value: 0.7480106100795756.
[I 2026-05-13 23:13:19,263] Trial 7 finished with value: 0.7484948002189381 and parameters: {'n_estimators': 82, 'max_depth': 3, 'learning_rate': 0.10062882326614553, 'subsample': 0.6846512464000236, 'colsample_bytree': 0.7062186637488905, 'reg_alpha': 0.09253214657642585, 'reg_lambda': 0.0016347456126376775}. Best is trial 7 with value: 0.7484948002189381.
[I 2026-05-13 23:13:19,879] Trial 8 finished with value: 0.7498432601880878 and parameters: {'n_estimators': 194, 'max_depth': 3, 'learning_rate': 0.07421227309649739, 'subsample': 0.8799033440083724, 'colsample_bytree': 0.6409337715311303, 'reg_alpha': 0.045313118440918, 'reg_lambda': 0.5992397731141761}. Best is trial 8 with value: 0.7498432601880878.
[I 2026-05-13 23:13:20,592] Trial 9 finished with value: 0.7071604938271605 and parameters: {'n_estimators': 153, 'max_depth': 3, 'learning_rate': 0.06188479711927507, 'subsample': 0.8655178580879155, 'colsample_bytree': 0.8059556448233234, 'reg_alpha': 6.003147633638413, 'reg_lambda': 0.2219321201267234}. Best is trial 8 with value: 0.7498432601880878.
[I 2026-05-13 23:13:21,094] Trial 10 finished with value: 0.7542796384901648 and parameters: {'n_estimators': 223, 'max_depth': 5, 'learning_rate': 0.26832720595321485, 'subsample': 0.9950624727138995, 'colsample_bytree': 0.603763117817339, 'reg_alpha': 0.4852851779481786, 'reg_lambda': 0.05452847267542391}. Best is trial 10 with value: 0.7542796384901648.
[I 2026-05-13 23:13:21,449] Trial 11 finished with value: 0.7541081311196254 and parameters: {'n_estimators': 221, 'max_depth': 5, 'learning_rate': 0.29111306222032063, 'subsample': 0.9985887837325315, 'colsample_bytree': 0.6012718691488821, 'reg_alpha': 0.6560936949146107, 'reg_lambda': 0.06709240882544949}. Best is trial 10 with value: 0.7542796384901648.
[I 2026-05-13 23:13:21,898] Trial 12 finished with value: 0.748206861894102 and parameters: {'n_estimators': 217, 'max_depth': 5, 'learning_rate': 0.2648132559079307, 'subsample': 0.9982982652868273, 'colsample_bytree': 0.6039370800781295, 'reg_alpha': 0.8268262415040837, 'reg_lambda': 0.05023907458622899}. Best is trial 10 with value: 0.7542796384901648.
[I 2026-05-13 23:13:22,642] Trial 13 finished with value: 0.7572025675473952 and parameters: {'n_estimators': 243, 'max_depth': 6, 'learning_rate': 0.2697850593761526, 'subsample': 0.9361115200877727, 'colsample_bytree': 0.7351173582042817, 'reg_alpha': 0.7465178584887114, 'reg_lambda': 0.07198157400748643}. Best is trial 13 with value: 0.7572025675473952.
[I 2026-05-13 23:13:23,221] Trial 14 finished with value: 0.7584291187739464 and parameters: {'n_estimators': 270, 'max_depth': 6, 'learning_rate': 0.16283760492313865, 'subsample': 0.9254774612956733, 'colsample_bytree': 0.7499154498067613, 'reg_alpha': 0.8844327435090215, 'reg_lambda': 0.0233427338556122}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:23,612] Trial 15 finished with value: 0.7381882485330761 and parameters: {'n_estimators': 282, 'max_depth': 6, 'learning_rate': 0.1523604106144241, 'subsample': 0.9253978450012961, 'colsample_bytree': 0.7485991545478111, 'reg_alpha': 2.1321980540250953, 'reg_lambda': 0.012741433732929271}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:24,111] Trial 16 finished with value: 0.7370005473453749 and parameters: {'n_estimators': 260, 'max_depth': 6, 'learning_rate': 0.03184216089383425, 'subsample': 0.9133911333012987, 'colsample_bytree': 0.7752040171507363, 'reg_alpha': 1.8013579261466668, 'reg_lambda': 8.443904558826752}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:25,114] Trial 17 finished with value: 0.7215956558061821 and parameters: {'n_estimators': 257, 'max_depth': 6, 'learning_rate': 0.1845316813775089, 'subsample': 0.8416935772538381, 'colsample_bytree': 0.8294359270360218, 'reg_alpha': 0.22541014931824702, 'reg_lambda': 0.24413313401669692}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:25,714] Trial 18 finished with value: 0.7419869189984132 and parameters: {'n_estimators': 253, 'max_depth': 8, 'learning_rate': 0.11570082873354008, 'subsample': 0.9505141509063619, 'colsample_bytree': 0.7321432851993185, 'reg_alpha': 2.0797630898362223, 'reg_lambda': 0.020231768659462662}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:26,070] Trial 19 finished with value: 0.7339338913321037 and parameters: {'n_estimators': 191, 'max_depth': 4, 'learning_rate': 0.2140013245022269, 'subsample': 0.8941515312491931, 'colsample_bytree': 0.6996927326872096, 'reg_alpha': 0.3712522800170135, 'reg_lambda': 0.00510859844940044}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:26,487] Trial 20 finished with value: 0.7249299417006821 and parameters: {'n_estimators': 242, 'max_depth': 6, 'learning_rate': 0.1399403139508959, 'subsample': 0.9493518953102481, 'colsample_bytree': 0.853342723238182, 'reg_alpha': 0.043269949968364994, 'reg_lambda': 0.113025631652363}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:26,961] Trial 21 finished with value: 0.7480106100795756 and parameters: {'n_estimators': 225, 'max_depth': 4, 'learning_rate': 0.29399938983536605, 'subsample': 0.9733023864737768, 'colsample_bytree': 0.7771072836681128, 'reg_alpha': 0.7853220247126442, 'reg_lambda': 0.02923279757343918}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:27,958] Trial 22 finished with value: 0.7420866982270491 and parameters: {'n_estimators': 277, 'max_depth': 5, 'learning_rate': 0.20676984418596878, 'subsample': 0.9107393969046482, 'colsample_bytree': 0.6966620598230937, 'reg_alpha': 0.38457463899920624, 'reg_lambda': 0.1526303253410493}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:28,331] Trial 23 finished with value: 0.7323126064815595 and parameters: {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.2215765490223727, 'subsample': 0.9616419096723119, 'colsample_bytree': 0.7402281604028391, 'reg_alpha': 4.069015868449336, 'reg_lambda': 0.047022929871512915}. Best is trial 14 with value: 0.7584291187739464.
[I 2026-05-13 23:13:28,711] Trial 24 finished with value: 0.7365985990784812 and parameters: {'n_estimators': 196, 'max_depth': 5, 'learning_rate': 0.08702407206167029, 'subsample': 0.8560180014731456, 'colsample_bytree': 0.6725094995546209, 'reg_alpha': 1.2680538255576304, 'reg_lambda': 0.008427228284802711}. Best is trial 14 with value: 0.7584291187739464.

done | Median MCC = 0.589
rnCV CatBoost ...

[I 2026-05-13 23:27:39,480] A new study created in memory with name: no-name-4de69a57-5f9e-44f0-b74e-c3ae9f5d0682
[I 2026-05-13 23:27:41,528] Trial 0 finished with value: 0.7638085742771685 and parameters: {'iterations': 187, 'depth': 7, 'learning_rate': 0.07768811685516967, 'l2_leaf_reg': 0.15119336467641012}. Best is trial 0 with value: 0.7638085742771685.
[I 2026-05-13 23:27:42,600] Trial 1 finished with value: 0.7640999493824286 and parameters: {'iterations': 156, 'depth': 6, 'learning_rate': 0.04429649570464297, 'l2_leaf_reg': 3.6905577292137624}. Best is trial 1 with value: 0.7640999493824286.
[I 2026-05-13 23:27:43,943] Trial 2 finished with value: 0.7526056965088653 and parameters: {'iterations': 291, 'depth': 5, 'learning_rate': 0.1477317633429356, 'l2_leaf_reg': 0.13049073550362397}. Best is trial 1 with value: 0.7640999493824286.
[I 2026-05-13 23:27:47,101] Trial 3 finished with value: 0.7703887510339124 and parameters: {'iterations': 192, 'depth': 8, 'learning_rate': 0.012732945242475176, 'l2_leaf_reg': 0.002231090560744304}. Best is trial 3 with value: 0.7703887510339124.
[I 2026-05-13 23:27:47,804] Trial 4 finished with value: 0.7704113352128967 and parameters: {'iterations': 55, 'depth': 7, 'learning_rate': 0.1410690937355148, 'l2_leaf_reg': 3.0202896401586674}. Best is trial 4 with value: 0.7704113352128967.
[I 2026-05-13 23:27:50,853] Trial 5 finished with value: 0.776333628057766 and parameters: {'iterations': 295, 'depth': 7, 'learning_rate': 0.048046413497514796, 'l2_leaf_reg': 1.3246974647468452}. Best is trial 5 with value: 0.776333628057766.
[I 2026-05-13 23:27:51,456] Trial 6 finished with value: 0.7703887510339124 and parameters: {'iterations': 79, 'depth': 6, 'learning_rate': 0.01628359108363256, 'l2_leaf_reg': 6.007249475906204}. Best is trial 5 with value: 0.776333628057766.
[I 2026-05-13 23:27:52,348] Trial 7 finished with value: 0.7603719681717956 and parameters: {'iterations': 180, 'depth': 5, 'learning_rate': 0.024591256383397347, 'l2_leaf_reg': 1.2500712230836255}. Best is trial 5 with value: 0.776333628057766.
[I 2026-05-13 23:27:53,458] Trial 8 finished with value: 0.7581434142602737 and parameters: {'iterations': 164, 'depth': 6, 'learning_rate': 0.010659941309425505, 'l2_leaf_reg': 0.2954894558726685}. Best is trial 5 with value: 0.776333628057766.
[I 2026-05-13 23:27:54,790] Trial 9 finished with value: 0.747123695976155 and parameters: {'iterations': 203, 'depth': 6, 'learning_rate': 0.247759517096838, 'l2_leaf_reg': 0.5336803302756715}. Best is trial 5 with value: 0.776333628057766.
[I 2026-05-13 23:27:55,801] Trial 10 finished with value: 0.7277252940631657 and parameters: {'iterations': 292, 'depth': 3, 'learning_rate': 0.04236022459266504, 'l2_leaf_reg': 0.018793823354596277}. Best is trial 5 with value: 0.776333628057766.
[I 2026-05-13 23:27:56,777] Trial 11 finished with value: 0.7912280701754386 and parameters: {'iterations': 56, 'depth': 8, 'learning_rate': 0.08607413555889588, 'l2_leaf_reg': 1.8162906176474265}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:00,974] Trial 12 finished with value: 0.7767822245820519 and parameters: {'iterations': 244, 'depth': 8, 'learning_rate': 0.07211957660694798, 'l2_leaf_reg': 1.0192381256167131}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:05,158] Trial 13 finished with value: 0.7564552406657671 and parameters: {'iterations': 245, 'depth': 8, 'learning_rate': 0.07819820116071069, 'l2_leaf_reg': 0.019885967449058677}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:07,195] Trial 14 finished with value: 0.7649463671321595 and parameters: {'iterations': 114, 'depth': 8, 'learning_rate': 0.10337671438419851, 'l2_leaf_reg': 8.610914254616409}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:08,035] Trial 15 finished with value: 0.7711839708561019 and parameters: {'iterations': 239, 'depth': 3, 'learning_rate': 0.028701035287102016, 'l2_leaf_reg': 0.04017860544913712}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:08,581] Trial 16 finished with value: 0.7776047460140898 and parameters: {'iterations': 121, 'depth': 4, 'learning_rate': 0.2817846508197404, 'l2_leaf_reg': 1.0561081103572054}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:09,121] Trial 17 finished with value: 0.7685019785189372 and parameters: {'iterations': 113, 'depth': 4, 'learning_rate': 0.26311431046628536, 'l2_leaf_reg': 0.4091405891062585}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:09,656] Trial 18 finished with value: 0.7411114436353022 and parameters: {'iterations': 116, 'depth': 4, 'learning_rate': 0.17632759098084885, 'l2_leaf_reg': 0.00103782366977728}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:10,066] Trial 19 finished with value: 0.7802951689150236 and parameters: {'iterations': 84, 'depth': 4, 'learning_rate': 0.1869077991750725, 'l2_leaf_reg': 2.2962189271167732}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:10,416] Trial 20 finished with value: 0.7785089773614363 and parameters: {'iterations': 50, 'depth': 5, 'learning_rate': 0.11020720018510549, 'l2_leaf_reg': 0.04689462256162329}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:10,760] Trial 21 finished with value: 0.7733426704014938 and parameters: {'iterations': 50, 'depth': 5, 'learning_rate': 0.11483045978433072, 'l2_leaf_reg': 0.05032864686595619}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:11,163] Trial 22 finished with value: 0.7523878776413464 and parameters: {'iterations': 84, 'depth': 4, 'learning_rate': 0.20153421500996527, 'l2_leaf_reg': 0.01301448044080698}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:11,629] Trial 23 finished with value: 0.7638085742771685 and parameters: {'iterations': 76, 'depth': 5, 'learning_rate': 0.10173040791488708, 'l2_leaf_reg': 0.006740460328341053}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:12,037] Trial 24 finished with value: 0.7890047805302043 and parameters: {'iterations': 96, 'depth': 3, 'learning_rate': 0.06226848359476931, 'l2_leaf_reg': 0.07025527130753796}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:12,582] Trial 25 finished with value: 0.7671201814058958 and parameters: {'iterations': 142, 'depth': 3, 'learning_rate': 0.057331587129018466, 'l2_leaf_reg': 2.4316203203280806}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:12,973] Trial 26 finished with value: 0.7548428694580404 and parameters: {'iterations': 96, 'depth': 3, 'learning_rate': 0.030829505165582728, 'l2_leaf_reg': 0.27015579264336315}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:13,588] Trial 27 finished with value: 0.7857315905446406 and parameters: {'iterations': 137, 'depth': 4, 'learning_rate': 0.06166178351803719, 'l2_leaf_reg': 0.07518366200442936}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:14,167] Trial 28 finished with value: 0.7587559161595672 and parameters: {'iterations': 141, 'depth': 3, 'learning_rate': 0.036669132007786945, 'l2_leaf_reg': 0.0988121158421544}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:15,309] Trial 29 finished with value: 0.77081793277384 and parameters: {'iterations': 99, 'depth': 7, 'learning_rate': 0.06511541202414568, 'l2_leaf_reg': 0.08571002403890259}. Best is trial 11 with value: 0.7912280701754386.
[I 2026-05-13 23:28:15,704] A new study created in memory with name: no-name-f991092d-68ed-4fc0-953d-f1fb8d93780d
[I 2026-05-13 23:28:17,331] Trial 0 finished with value: 0.7052368535419383 and parameters: {'iterations': 154, 'depth': 7, 'learning_rate': 0.010003890870040017, 'l2_leaf_reg': 0.016193110912440738}. Best is trial 0 with value: 0.7052368535419383.
[I 2026-05-13 23:28:17,700] Trial 1 finished with value: 0.7091767881241565 and parameters: {'iterations': 86, 'depth': 3, 'learning_rate': 0.018842083199166547, 'l2_leaf_reg': 0.024112537061475744}. Best is trial 1 with value: 0.7091767881241565.
[I 2026-05-13 23:28:18,765] Trial 2 finished with value: 0.7170940170940172 and parameters: {'iterations': 149, 'depth': 6, 'learning_rate': 0.04161032683929613, 'l2_leaf_reg': 0.5506529897945993}. Best is trial 2 with value: 0.7170940170940172.
[I 2026-05-13 23:28:20,456] Trial 3 finished with value: 0.7293390709478098 and parameters: {'iterations': 101, 'depth': 8, 'learning_rate': 0.010976270367293662, 'l2_leaf_reg': 0.4806954824961602}. Best is trial 3 with value: 0.7293390709478098.
[I 2026-05-13 23:28:21,501] Trial 4 finished with value: 0.7319161350770594 and parameters: {'iterations': 154, 'depth': 6, 'learning_rate': 0.01612012966795156, 'l2_leaf_reg': 0.006200203677164719}. Best is trial 4 with value: 0.7319161350770594.
[I 2026-05-13 23:28:25,724] Trial 5 finished with value: 0.7007051648561081 and parameters: {'iterations': 250, 'depth': 8, 'learning_rate': 0.029037920727453637, 'l2_leaf_reg': 0.5878824056644089}. Best is trial 4 with value: 0.7319161350770594.
[I 2026-05-13 23:28:30,086] Trial 6 finished with value: 0.6779220779220779 and parameters: {'iterations': 269, 'depth': 8, 'learning_rate': 0.013354284130669362, 'l2_leaf_reg': 0.0014329107238467847}. Best is trial 4 with value: 0.7319161350770594.
[I 2026-05-13 23:28:31,631] Trial 7 finished with value: 0.7207885533041644 and parameters: {'iterations': 92, 'depth': 8, 'learning_rate': 0.013972373892609564, 'l2_leaf_reg': 0.048353787772855095}. Best is trial 4 with value: 0.7319161350770594.
[I 2026-05-13 23:28:33,479] Trial 8 finished with value: 0.7250766005482987 and parameters: {'iterations': 290, 'depth': 6, 'learning_rate': 0.10519289093896142, 'l2_leaf_reg': 0.018283634209844524}. Best is trial 4 with value: 0.7319161350770594.
[I 2026-05-13 23:28:37,054] Trial 9 finished with value: 0.7349477682811015 and parameters: {'iterations': 222, 'depth': 8, 'learning_rate': 0.010641773304807034, 'l2_leaf_reg': 1.0013300735281483}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:38,007] Trial 10 finished with value: 0.691358024691358 and parameters: {'iterations': 235, 'depth': 4, 'learning_rate': 0.26832720595321485, 'l2_leaf_reg': 8.92533913927227}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:39,025] Trial 11 finished with value: 0.7175200278648554 and parameters: {'iterations': 199, 'depth': 5, 'learning_rate': 0.026299516915711068, 'l2_leaf_reg': 0.0013526932974406497}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:40,082] Trial 12 finished with value: 0.7176829018934283 and parameters: {'iterations': 199, 'depth': 5, 'learning_rate': 0.07456707476566436, 'l2_leaf_reg': 5.473251076892465}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:41,464] Trial 13 finished with value: 0.7232590395363848 and parameters: {'iterations': 128, 'depth': 7, 'learning_rate': 0.02181968639253355, 'l2_leaf_reg': 0.16395131410388572}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:42,157] Trial 14 finished with value: 0.724867724867725 and parameters: {'iterations': 53, 'depth': 7, 'learning_rate': 0.044132287920580916, 'l2_leaf_reg': 0.005055052777369692}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:42,954] Trial 15 finished with value: 0.7105420784666068 and parameters: {'iterations': 202, 'depth': 4, 'learning_rate': 0.155697395429314, 'l2_leaf_reg': 2.1842138941612292}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:44,445] Trial 16 finished with value: 0.7217810438149422 and parameters: {'iterations': 224, 'depth': 6, 'learning_rate': 0.01940050902222285, 'l2_leaf_reg': 0.17208372783966586}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:46,342] Trial 17 finished with value: 0.7171717171717171 and parameters: {'iterations': 175, 'depth': 7, 'learning_rate': 0.03823137328350896, 'l2_leaf_reg': 0.004445562973849754}. Best is trial 9 with value: 0.7349477682811015.
[I 2026-05-13 23:28:47,038] Trial 18 finished with value: 0.7608311229000884 and parameters: {'iterations': 132, 'depth': 5, 'learning_rate': 0.015448761343957512, 'l2_leaf_reg': 1.4684483261994552}. Best is trial 18 with value: 0.7608311229000884.
[I 2026-05-13 23:28:47,559] Trial 19 finished with value: 0.714100064977258 and parameters: {'iterations': 118, 'depth': 4, 'learning_rate': 0.06753747328344378, 'l2_leaf_reg': 2.2336411728267076}. Best is trial 18 with value: 0.7608311229000884.
[I 2026-05-13 23:28:48,252] Trial 20 finished with value: 0.7091767881241565 and parameters: {'iterations': 177, 'depth': 3, 'learning_rate': 0.030296064266778194, 'l2_leaf_reg': 1.751359510298957}. Best is trial 18 with value: 0.7608311229000884.
[I 2026-05-13 23:28:49,022] Trial 21 finished with value: 0.7654691547613507 and parameters: {'iterations': 146, 'depth': 5, 'learning_rate': 0.015045890828891515, 'l2_leaf_reg': 1.213282071300435}. Best is trial 21 with value: 0.7654691547613507.
[I 2026-05-13 23:28:49,715] Trial 22 finished with value: 0.7418672739102147 and parameters: {'iterations': 121, 'depth': 5, 'learning_rate': 0.013385832823155728, 'l2_leaf_reg': 1.1153125069516787}. Best is trial 21 with value: 0.7654691547613507.
[I 2026-05-13 23:28:50,442] Trial 23 finished with value: 0.76003996003996 and parameters: {'iterations': 131, 'depth': 5, 'learning_rate': 0.014667013701976308, 'l2_leaf_reg': 4.445892574095081}. Best is trial 21 with value: 0.7654691547613507.
[I 2026-05-13 23:28:50,830] Trial 24 finished with value: 0.7557225660673937 and parameters: {'iterations': 62, 'depth': 5, 'learning_rate': 0.019222639867563042, 'l2_leaf_reg': 4.788978191795088}. Best is trial 21 with value: 0.7654691547613507.
[I 2026-05-13 23:28:51,408] Trial 25 finished with value: 0.7092418588619641 and parameters: {'iterations': 137, 'depth': 4, 'learning_rate': 0.024341022686685348, 'l2_leaf_reg': 0.25008435927738876}. Best is trial 21 with value: 0.7654691547613507.
[I 2026-05-13 23:28:52,061] Trial 26 finished with value: 0.7698623215864595 and parameters: {'iterations': 106, 'depth': 5, 'learning_rate': 0.01561446630673939, 'l2_leaf_reg': 3.23755994180542}. Best is trial 26 with value: 0.7698623215864595.
[I 2026-05-13 23:28:52,601] Trial 27 finished with value: 0.721712899982256 and parameters: {'iterations': 104, 'depth': 4, 'learning_rate': 0.03422227848368872, 'l2_leaf_reg': 0.0654387374889173}. Best is trial 26 with value: 0.7698623215864595.
[I 2026-05-13 23:28:53,518] Trial 28 finished with value: 0.7337817159531689 and parameters: {'iterations': 173, 'depth': 5, 'learning_rate': 0.05305972798275393, 'l2_leaf_reg': 9.807707941889644}. Best is trial 26 with value: 0.7698623215864595.
[I 2026-05-13 23:28:54,121] Trial 29 finished with value: 0.7025252525252524 and parameters: {'iterations': 74, 'depth': 6, 'learning_rate': 0.01045809894702782, 'l2_leaf_reg': 0.31687387191029204}. Best is trial 26 with value: 0.7698623215864595.
[I 2026-05-13 23:28:54,344] A new study created in memory with name: no-name-48c405bf-fd87-4749-a319-5b1e30df8acf
[I 2026-05-13 23:28:54,957] Trial 0 finished with value: 0.7376215738284704 and parameters: {'iterations': 159, 'depth': 3, 'learning_rate': 0.06485121677838487, 'l2_leaf_reg': 0.05511750757691416}. Best is trial 0 with value: 0.7376215738284704.
[I 2026-05-13 23:28:55,662] Trial 1 finished with value: 0.7633024597411256 and parameters: {'iterations': 155, 'depth': 4, 'learning_rate': 0.020058148722162418, 'l2_leaf_reg': 0.2999741734865517}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:28:56,282] Trial 2 finished with value: 0.709963555314599 and parameters: {'iterations': 125, 'depth': 4, 'learning_rate': 0.08269704407704705, 'l2_leaf_reg': 0.13078814409401443}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:28:56,912] Trial 3 finished with value: 0.742432192303118 and parameters: {'iterations': 83, 'depth': 6, 'learning_rate': 0.018725785562119596, 'l2_leaf_reg': 1.3846518531662901}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:28:58,131] Trial 4 finished with value: 0.7030503978779841 and parameters: {'iterations': 264, 'depth': 5, 'learning_rate': 0.1780221178946605, 'l2_leaf_reg': 0.002082485125344959}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:28:58,778] Trial 5 finished with value: 0.7202769996887644 and parameters: {'iterations': 176, 'depth': 3, 'learning_rate': 0.04289321404485208, 'l2_leaf_reg': 0.002432896662591013}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:28:59,425] Trial 6 finished with value: 0.7460378720469416 and parameters: {'iterations': 81, 'depth': 6, 'learning_rate': 0.021569850245884092, 'l2_leaf_reg': 0.0026778283632142423}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:29:00,048] Trial 7 finished with value: 0.7220568783068783 and parameters: {'iterations': 105, 'depth': 5, 'learning_rate': 0.049088395404691273, 'l2_leaf_reg': 0.006411695737901102}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:29:01,117] Trial 8 finished with value: 0.7106060606060606 and parameters: {'iterations': 210, 'depth': 5, 'learning_rate': 0.05575655055826314, 'l2_leaf_reg': 0.03528341431945178}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:29:02,776] Trial 9 finished with value: 0.7504819469206128 and parameters: {'iterations': 249, 'depth': 6, 'learning_rate': 0.01736739610241428, 'l2_leaf_reg': 0.6353446634397301}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:29:07,297] Trial 10 finished with value: 0.7607827764424316 and parameters: {'iterations': 291, 'depth': 8, 'learning_rate': 0.010385377243179483, 'l2_leaf_reg': 6.1119118800301955}. Best is trial 1 with value: 0.7633024597411256.
[I 2026-05-13 23:29:11,636] Trial 11 finished with value: 0.7700008556515786 and parameters: {'iterations': 283, 'depth': 8, 'learning_rate': 0.010104900253241025, 'l2_leaf_reg': 6.628753453031315}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:14,956] Trial 12 finished with value: 0.7524844270606983 and parameters: {'iterations': 209, 'depth': 8, 'learning_rate': 0.01158139108870447, 'l2_leaf_reg': 9.790374806374121}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:16,540] Trial 13 finished with value: 0.7361073461642723 and parameters: {'iterations': 147, 'depth': 7, 'learning_rate': 0.02688377673540725, 'l2_leaf_reg': 0.9067139193476054}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:17,350] Trial 14 finished with value: 0.7174682978604547 and parameters: {'iterations': 202, 'depth': 4, 'learning_rate': 0.030239221817198604, 'l2_leaf_reg': 0.23752324195022398}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:19,813] Trial 15 finished with value: 0.7530840806702876 and parameters: {'iterations': 243, 'depth': 7, 'learning_rate': 0.013824506795362537, 'l2_leaf_reg': 2.4821172423857347}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:20,146] Trial 16 finished with value: 0.7334053081421503 and parameters: {'iterations': 55, 'depth': 4, 'learning_rate': 0.2940223438153275, 'l2_leaf_reg': 0.015886257129939702}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:23,136] Trial 17 finished with value: 0.7106060606060606 and parameters: {'iterations': 293, 'depth': 7, 'learning_rate': 0.03333232830667354, 'l2_leaf_reg': 0.292791126068386}. Best is trial 11 with value: 0.7700008556515786.
[I 2026-05-13 23:29:23,840] Trial 18 finished with value: 0.7590651009169093 and parameters: {'iterations': 182, 'depth': 4, 'learning_rate': 0.014699726620750345, 'l2_leaf_reg': 3.125633618808737}. Best is trial 11 with value: 0.7700008556515786.

done | Median MCC = 0.623

rnCV complete.

In [ ]:
METRICS = ["mcc", "auc", "prauc", "ba", "f1", "recall", "specificity", "precision"]

rows = []
for name, df_res in rncv_results.items():
    for metric in METRICS:
        med = df_res[metric].median()
        lo, hi = functions.median_ci(df_res[metric])
        rows.append({
            "Algorithm" : name,
            "Metric"    : metric.upper(),
            "Median"    : round(med, 3),
            "95% CI"    : f"[{lo:.3f}, {hi:.3f}]",
        })

comparison_df = pd.DataFrame(rows)

# Wide pivot: algorithms as rows, metrics as columns (sorted by MCC)
pivot = (
    comparison_df
    .pivot(index="Algorithm", columns="Metric", values="Median")
    [["MCC", "AUC", "PRAUC", "BA", "F1", "RECALL", "SPECIFICITY", "PRECISION"]]
    .sort_values("MCC", ascending=False)
)
print("Median performance across 50 rnCV evaluation points (sorted by MCC):")
display(pivot)

print("\n95% Bootstrap CIs:")
display(
    comparison_df
    .pivot(index="Algorithm", columns="Metric", values="95% CI")
    .reindex(pivot.index)
)

Median performance across 50 rnCV evaluation points (sorted by MCC):

Metric,MCC,AUC,PRAUC,BA,F1,RECALL,SPECIFICITY,PRECISION
Algorithm,,,,,,,,
LDA,0.656,0.897,0.892,0.819,0.800,0.773,0.885,0.834
LR_ElasticNet,0.627,0.894,0.893,0.808,0.782,0.773,0.885,0.841
CatBoost,0.623,0.887,0.881,0.805,0.780,0.756,0.846,0.810
LightGBM,0.606,0.880,0.873,0.798,0.776,0.773,0.846,0.810
RandomForest,0.592,0.896,0.892,0.795,0.777,0.756,0.846,0.800
XGBoost,0.589,0.879,0.881,0.793,0.773,0.773,0.846,0.800
GNB,0.532,0.877,0.868,0.760,0.760,0.867,0.654,0.667

95% Bootstrap CIs:

Metric,AUC,BA,F1,MCC,PRAUC,PRECISION,RECALL,SPECIFICITY
Algorithm,,,,,,,,
LDA,"[0.886, 0.903]","[0.803, 0.834]","[0.780, 0.818]","[0.623, 0.673]","[0.878, 0.904]","[0.800, 0.854]","[0.727, 0.783]","[0.846, 0.885]"
LR_ElasticNet,"[0.885, 0.908]","[0.790, 0.832]","[0.769, 0.817]","[0.599, 0.669]","[0.877, 0.903]","[0.809, 0.850]","[0.727, 0.818]","[0.846, 0.885]"
CatBoost,"[0.874, 0.897]","[0.776, 0.813]","[0.757, 0.800]","[0.551, 0.644]","[0.873, 0.896]","[0.762, 0.850]","[0.727, 0.773]","[0.808, 0.885]"
LightGBM,"[0.848, 0.890]","[0.778, 0.812]","[0.762, 0.791]","[0.557, 0.632]","[0.857, 0.894]","[0.762, 0.833]","[0.733, 0.795]","[0.808, 0.885]"
RandomForest,"[0.878, 0.913]","[0.779, 0.818]","[0.756, 0.800]","[0.560, 0.635]","[0.877, 0.908]","[0.771, 0.834]","[0.727, 0.773]","[0.808, 0.885]"
XGBoost,"[0.865, 0.895]","[0.781, 0.808]","[0.762, 0.791]","[0.568, 0.632]","[0.874, 0.894]","[0.762, 0.842]","[0.727, 0.773]","[0.808, 0.885]"
GNB,"[0.863, 0.883]","[0.740, 0.779]","[0.743, 0.774]","[0.493, 0.572]","[0.855, 0.879]","[0.645, 0.691]","[0.864, 0.909]","[0.577, 0.667]"

In [19]:
WINNER_NAME = pivot.index[0]

winner_name, winner_clf, winner_space = next(
    (n, c, s) for n, c, s in ALGORITHMS if n == WINNER_NAME
)

print(f"Winner : {winner_name}")
display(rncv_results[winner_name][METRICS].describe().T[["mean", "50%", "std"]])

Winner : LDA

                 mean       50%       std
mcc          0.639722  0.655575  0.110891
auc          0.895997  0.897423  0.039105
prauc        0.891966  0.891797  0.041050
ba           0.815333  0.819412  0.055018
f1           0.795152  0.800000  0.062634
recall       0.768300  0.772727  0.084731
specificity  0.862365  0.884615  0.073643
precision    0.831701  0.834096  0.079131

## Task 4 - Feature Selection

In [21]:
print(f"Running rnCV + feature selection for {winner_name} ...")

fs_results = rncv.run_assessment(
    X, y,
    estimator_name = winner_name,
    estimator = winner_clf,
    param_space_func = winner_space,
    perform_fs = True, # RFECV selector inserted into the pipeline
    tune = True, # inner hyperparameter tuning remains active
)

print("\nFeature-selection rnCV complete.")

[I 2026-05-14 00:07:18,846] A new study created in memory with name: no-name-878584cd-2028-41ef-9def-fcf2e133b112

[I 2026-05-14 00:07:18,911] Trial 0 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:18,989] Trial 1 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.

Running rnCV + feature selection for LDA ...

[I 2026-05-14 00:07:19,058] Trial 2 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,135] Trial 3 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,205] Trial 4 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,275] Trial 5 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,342] Trial 6 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,402] Trial 7 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,476] Trial 8 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,549] Trial 9 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,623] Trial 10 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,685] Trial 11 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,757] Trial 12 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,823] Trial 13 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,892] Trial 14 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:19,971] Trial 15 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,049] Trial 16 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,118] Trial 17 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,204] Trial 18 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,278] Trial 19 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,353] Trial 20 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,425] Trial 21 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,496] Trial 22 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,565] Trial 23 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,630] Trial 24 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,692] Trial 25 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,761] Trial 26 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,824] Trial 27 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,889] Trial 28 finished with value: 0.8342472342472341 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:20,961] Trial 29 finished with value: 0.8145021645021645 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.8342472342472341.
[I 2026-05-14 00:07:30,378] A new study created in memory with name: no-name-76f5775d-59bb-43eb-8ae7-866b4c379b89
[I 2026-05-14 00:07:30,446] Trial 0 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,519] Trial 1 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,591] Trial 2 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,654] Trial 3 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,737] Trial 4 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,805] Trial 5 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,874] Trial 6 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:30,942] Trial 7 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,011] Trial 8 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,076] Trial 9 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,145] Trial 10 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,217] Trial 11 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,281] Trial 12 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,343] Trial 13 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,420] Trial 14 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,487] Trial 15 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,555] Trial 16 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,622] Trial 17 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,688] Trial 18 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,756] Trial 19 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,833] Trial 20 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,908] Trial 21 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:31,981] Trial 22 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,059] Trial 23 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,133] Trial 24 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,211] Trial 25 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,286] Trial 26 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,351] Trial 27 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,422] Trial 28 finished with value: 0.770122158004488 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:32,490] Trial 29 finished with value: 0.7687879756955548 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.770122158004488.
[I 2026-05-14 00:07:42,212] A new study created in memory with name: no-name-a2a33572-0d85-48be-9dda-f759e8138ffa
[I 2026-05-14 00:07:42,289] Trial 0 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,370] Trial 1 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,455] Trial 2 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,535] Trial 3 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,616] Trial 4 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,694] Trial 5 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,768] Trial 6 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,843] Trial 7 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:42,923] Trial 8 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,003] Trial 9 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,075] Trial 10 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,152] Trial 11 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,227] Trial 12 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,304] Trial 13 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,379] Trial 14 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,455] Trial 15 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,531] Trial 16 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,606] Trial 17 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,679] Trial 18 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,756] Trial 19 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,831] Trial 20 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,907] Trial 21 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:43,983] Trial 22 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,058] Trial 23 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,134] Trial 24 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,210] Trial 25 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,285] Trial 26 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,365] Trial 27 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,451] Trial 28 finished with value: 0.806670311645708 and parameters: {'shrinkage': 'auto'}. Best is trial 0 with value: 0.806670311645708.
[I 2026-05-14 00:07:44,530] Trial 29 finished with value: 0.769706498951782 and parameters: {'shrinkage': None}. Best is trial 0 with value: 0.806670311645708.

ValueError: operands could not be broadcast together with shapes (22,) (21,) (22,)

In [ ]:
full_res = rncv_results[winner_name] # all features, tuned
fs_res = fs_results # selected features, tuned

compare_rows = []
for metric in METRICS:
    med_full, med_fs = full_res[metric].median(), fs_res[metric].median()
    lo_full, hi_full = functions.median_ci(full_res[metric])
    lo_fs, hi_fs = functions.median_ci(fs_res[metric])
    compare_rows.append({
        "Metric"        : metric.upper(),
        "Full Median"   : round(med_full, 3),
        "Full 95% CI"   : f"[{lo_full:.3f}, {hi_full:.3f}]",
        "FS Median"     : round(med_fs, 3),
        "FS 95% CI"     : f"[{lo_fs:.3f}, {hi_fs:.3f}]",
        "Delta (FS-Full)": round(med_fs - med_full, 3),
    })

compare_df = pd.DataFrame(compare_rows).set_index("Metric")
print(f"{winner_name}: Full features vs. RFECV-selected subset")
display(compare_df)